# Pandas Nedir?

Pandas, Python programlama diliyle veri analizi ve veri işleme işlemlerini kolaylaştırmak için geliştirilmiş açık kaynak kodlu bir kütüphanedir.

Özellikle tablo (DataFrame) ve seri (Series) gibi veri yapıları sunarak, düzenli ve karmaşık veriler üzerinde kolayca işlem yapmayı mümkün kılar.

Pandas ile:

- CSV, Excel gibi dosya tiplerinden veri okuyabilir ve kaydedebilirsiniz.
- Verileri filtreleyebilir, gruplayabilir, özetleyebilir ve dönüştürebilirsiniz.
- Eksik verilerle (NaN) kolayca başa çıkabilirsiniz.
- İstatistiksel analizler ve veri temizleme işlemleri gerçekleştirebilirsiniz.

Pandas, veri bilimi, makine öğrenimi ve istatistiksel analiz gibi alanlarda temel bir araçtır ve veriyle çalışanlar için oldukça gereklidir.

## Pandas Series Nedir?

Pandas `Series`, tek boyutlu (1D) veri tutmak için kullanılan özel bir veri yapısıdır. Bir `Series`; bir veri dizisi ve her veri için bir etiket (index) içerir. Bu sayede, verileri kolayca erişilebilir ve işlenebilir hale getirir.

**Temel Özellikleri:**
- Bir `Series`, Python'un yerleşik listesi veya NumPy dizisi gibi düşünülebilir; fakat her öğenin bir etiketi (index) vardır.
- Veriler farklı veri tiplerinden oluşabilir (tamsayı, float, string vb.).
- Eksik değerlere (NaN) izin verir.

**Series Oluşturma Örneği:**
```python
import pandas as pd

veriler = [10, 20, 30, 40]
etiketler = ['a', 'b', 'c', 'd']

s = pd.Series(veriler, index=etiketler)
print(s)
```
Çıktı:
```
a    10
b    20
c    30
d    40
dtype: int64
```

**Kısaca:**  
Pandas Series, tek boyutlu veri kümelerini etiketlerle birlikte kolayca saklamanızı ve işlemenizi sağlar. Özellikle zaman serisi analizlerinde ve sütun bazlı veri işlemlerinde sıklıkla kullanılır.

In [2]:
import pandas as pd
import numpy as np

In [3]:
s = pd.Series([10,77,12,4,5])
print(s)

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [4]:
type(s)

pandas.Series

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s.dtype

dtype('int64')

In [7]:
s.size

5

In [8]:
s.ndim

1

In [9]:
s.values

array([10, 77, 12,  4,  5])

In [10]:
s.head() # ilk 5 veriyi getirir

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [11]:
s.tail() # son 5 veriyi getirir

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [12]:
df = pd.read_csv('datasets/advertising.csv') # csv dosyasını okur
print(df.head())
print("--------------------------------")
print(df.info())
print("--------------------------------")
print(df.describe())
print("--------------------------------")
print(df.isnull().sum())
print("--------------------------------")

      TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9
--------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB
None
--------------------------------
               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000
--------------------------------
TV           0
radio        0
newspaper    0
sales        0
dtype: int64
--------------------------------

In [13]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.head()) # ilk 5 veriyi getirir
print("--------------------------------")
print(df.tail()) # son 5 veriyi getirir
print("--------------------------------")
print(df.info()) # veri tiplerini getirir
print("--------------------------------")
print(df.index) # indexleri getirir
print("--------------------------------")
print(df.describe().T) # istatistiksel verileri getirir
print("--------------------------------")
print(df.isnull().values.any()) # eksik verileri getirir
print("--------------------------------")
print(df.isnull().sum()) # eksik verilerin sayısını getirir
print("--------------------------------")

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
--------------------------------
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second
887         1       1  female  19.0      0      0  30.00        S   First
888         0       3  female   NaN      1      2  23.45        S   Third
889         1       1    male  26.0      0      0  30.00        C   First
890         0       3    male  32.0      0      0   7.75        Q   Third

       who  adult_male deck  embark_town alive  alone
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True
--------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None
--------------------------------
RangeIndex(start=0, stop=891, step=1)
--------------------------------
          count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292
--------------------------------
True
--------------------------------
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
--------------------------------

## Pandas'ta Seçim İşlemleri (Selection in Pandas)

Pandas'ta veri seçme işlemleri farklı yöntemlerle yapılabilir. En yaygın seçim işlemleri şunlardır:

**1. Tek bir sütunu seçmek:**  
Bir DataFrame'den bir sütun seçmek için köşeli parantezler kullanılır:  
`df['column_name']`  
veya  
`df.column_name`

**2. Birden fazla sütunu seçmek:**  
Birden fazla sütun seçmek için sütun isimlerini bir liste içinde belirtirsiniz:  
`df[['column1', 'column2']]`

**3. Satıra göre seçim (loc ve iloc):**  
- `loc[]` etikete (index adı) göre seçim yapar:  
  `df.loc[2]` → indexi 2 olan satırı getirir  
  `df.loc[2:5]` → 2’den 5’e kadar (5 dahil) satırları getirir  
  `df.loc[:, 'column_name']` → tüm satırlarda sadece belirtilen sütunu getirir

- `iloc[]` pozisyona göre seçim yapar (0’dan başlar):  
  `df.iloc[0]` → ilk satırı getirir  
  `df.iloc[0:3]` → 0, 1 ve 2. satırları getirir  
  `df.iloc[:, 1]` → tüm satırlarda 2. sütunu getirir

**4. Koşullu seçim:**  
Belirli bir koşulu sağlayan satırları seçmek için boolean koşullar kullanılabilir:  
`df[df['age'] > 18]` → Yaşı 18’den büyük olanları seçer

**5. Belirli hücreye erişmek:**  
Belirli bir satır ve sütundaki değere ulaşmak için:  
`df.loc[3, 'age']` veya `df.iloc[3, 2]` kullanılabilir.

Bu yöntemler sayesinde Pandas'ta veri seçimini esnek ve kolay bir şekilde gerçekleştirebilirsiniz.

In [14]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [16]:
df[0:13]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.drop(0, axis=0) # 0. satırı siler. Geçici olarak siler. inplace=True yaparsak kalıcı olarak siler.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [18]:
delete_index = [1,3,5,7]
df.drop(delete_index, axis=0).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False

**Bir sütunu index olarak kullanmak:**  
Bir DataFrame'in belirli bir sütununu index olarak ayarlamak için `set_index()` fonksiyonu kullanılır.  
Örneğin, "age" sütununu index yapmak için:  
`df.set_index('age')`  
Bu işlem orijinal DataFrame'i değiştirmez, geçici olarak yeni bir DataFrame döndürür.  
Kalıcı olarak değiştirmek için `inplace=True` parametresi eklenir:  
`df.set_index('age', inplace=True)`

Index’i tekrar varsayılan hale getirmek için ise `reset_index()` fonksiyonu kullanılabilir.  
Örneğin:  
`df.reset_index()`  
Kalıcı yapmak için yine `inplace=True` kullanılmalıdır.

In [19]:
df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [20]:
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [21]:
df.index = df.age
df.index

Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
       ...
       33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],
      dtype='float64', name='age', length=891)

In [22]:
df.drop("age", axis=1).head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [23]:
df.drop("age", axis=1, inplace=True)
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

İndexi tekrar sütuna almak için `reset_index()` fonksiyonunu kullanabilirsiniz:

```python
df.reset_index(inplace=True)
df.head()
```

In [24]:
df["age"] = df.index
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age
age,,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,22.0
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,38.0
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,26.0
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,35.0
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,35.0