# Pandas Nedir?

Pandas, Python programlama diliyle veri analizi ve veri işleme işlemlerini kolaylaştırmak için geliştirilmiş açık kaynak kodlu bir kütüphanedir.

Özellikle tablo (DataFrame) ve seri (Series) gibi veri yapıları sunarak, düzenli ve karmaşık veriler üzerinde kolayca işlem yapmayı mümkün kılar.

Pandas ile:

- CSV, Excel gibi dosya tiplerinden veri okuyabilir ve kaydedebilirsiniz.
- Verileri filtreleyebilir, gruplayabilir, özetleyebilir ve dönüştürebilirsiniz.
- Eksik verilerle (NaN) kolayca başa çıkabilirsiniz.
- İstatistiksel analizler ve veri temizleme işlemleri gerçekleştirebilirsiniz.

Pandas, veri bilimi, makine öğrenimi ve istatistiksel analiz gibi alanlarda temel bir araçtır ve veriyle çalışanlar için oldukça gereklidir.

## Pandas Series Nedir?

Pandas `Series`, tek boyutlu (1D) veri tutmak için kullanılan özel bir veri yapısıdır. Bir `Series`; bir veri dizisi ve her veri için bir etiket (index) içerir. Bu sayede, verileri kolayca erişilebilir ve işlenebilir hale getirir.

**Temel Özellikleri:**
- Bir `Series`, Python'un yerleşik listesi veya NumPy dizisi gibi düşünülebilir; fakat her öğenin bir etiketi (index) vardır.
- Veriler farklı veri tiplerinden oluşabilir (tamsayı, float, string vb.).
- Eksik değerlere (NaN) izin verir.

**Series Oluşturma Örneği:**
```python
import pandas as pd

veriler = [10, 20, 30, 40]
etiketler = ['a', 'b', 'c', 'd']

s = pd.Series(veriler, index=etiketler)
print(s)
```
Çıktı:
```
a    10
b    20
c    30
d    40
dtype: int64
```

**Kısaca:**  
Pandas Series, tek boyutlu veri kümelerini etiketlerle birlikte kolayca saklamanızı ve işlemenizi sağlar. Özellikle zaman serisi analizlerinde ve sütun bazlı veri işlemlerinde sıklıkla kullanılır.

In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([10,77,12,4,5])
print(s)

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [3]:
type(s)

pandas.Series

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s.dtype

dtype('int64')

In [6]:
s.size

5

In [7]:
s.ndim

1

In [8]:
s.values

array([10, 77, 12,  4,  5])

In [9]:
s.head() # ilk 5 veriyi getirir

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [10]:
s.tail() # son 5 veriyi getirir

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [11]:
df = pd.read_csv('datasets/advertising.csv') # csv dosyasını okur
print(df.head())
print("--------------------------------")
print(df.info())
print("--------------------------------")
print(df.describe())
print("--------------------------------")
print(df.isnull().sum())
print("--------------------------------")

      TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9
--------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB
None
--------------------------------
               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000
--------------------------------
TV           0
radio        0
newspaper    0
sales        0
dtype: int64
--------------------------------

In [12]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.head()) # ilk 5 veriyi getirir
print("--------------------------------")
print(df.tail()) # son 5 veriyi getirir
print("--------------------------------")
print(df.info()) # veri tiplerini getirir
print("--------------------------------")
print(df.index) # indexleri getirir
print("--------------------------------")
print(df.describe().T) # istatistiksel verileri getirir
print("--------------------------------")
print(df.isnull().values.any()) # eksik verileri getirir
print("--------------------------------")
print(df.isnull().sum()) # eksik verilerin sayısını getirir
print("--------------------------------")

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
--------------------------------
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second
887         1       1  female  19.0      0      0  30.00        S   First
888         0       3  female   NaN      1      2  23.45        S   Third
889         1       1    male  26.0      0      0  30.00        C   First
890         0       3    male  32.0      0      0   7.75        Q   Third

       who  adult_male deck  embark_town alive  alone
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True
--------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None
--------------------------------
RangeIndex(start=0, stop=891, step=1)
--------------------------------
          count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292
--------------------------------
True
--------------------------------
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
--------------------------------

## Pandas'ta Seçim İşlemleri (Selection in Pandas)

Pandas'ta veri seçme işlemleri farklı yöntemlerle yapılabilir. En yaygın seçim işlemleri şunlardır:

**1. Tek bir sütunu seçmek:**  
Bir DataFrame'den bir sütun seçmek için köşeli parantezler kullanılır:  
`df['column_name']`  
veya  
`df.column_name`

**2. Birden fazla sütunu seçmek:**  
Birden fazla sütun seçmek için sütun isimlerini bir liste içinde belirtirsiniz:  
`df[['column1', 'column2']]`

**3. Satıra göre seçim (loc ve iloc):**  
- `loc[]` etikete (index adı) göre seçim yapar:  
  `df.loc[2]` → indexi 2 olan satırı getirir  
  `df.loc[2:5]` → 2’den 5’e kadar (5 dahil) satırları getirir  
  `df.loc[:, 'column_name']` → tüm satırlarda sadece belirtilen sütunu getirir

- `iloc[]` pozisyona göre seçim yapar (0’dan başlar):  
  `df.iloc[0]` → ilk satırı getirir  
  `df.iloc[0:3]` → 0, 1 ve 2. satırları getirir  
  `df.iloc[:, 1]` → tüm satırlarda 2. sütunu getirir

**4. Koşullu seçim:**  
Belirli bir koşulu sağlayan satırları seçmek için boolean koşullar kullanılabilir:  
`df[df['age'] > 18]` → Yaşı 18’den büyük olanları seçer

**5. Belirli hücreye erişmek:**  
Belirli bir satır ve sütundaki değere ulaşmak için:  
`df.loc[3, 'age']` veya `df.iloc[3, 2]` kullanılabilir.

Bu yöntemler sayesinde Pandas'ta veri seçimini esnek ve kolay bir şekilde gerçekleştirebilirsiniz.

In [13]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [14]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [15]:
df[0:13]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [16]:
df.drop(0, axis=0) # 0. satırı siler. Geçici olarak siler. inplace=True yaparsak kalıcı olarak siler.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
delete_index = [1,3,5,7]
df.drop(delete_index, axis=0).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False

**Bir sütunu index olarak kullanmak:**  
Bir DataFrame'in belirli bir sütununu index olarak ayarlamak için `set_index()` fonksiyonu kullanılır.  
Örneğin, "age" sütununu index yapmak için:  
`df.set_index('age')`  
Bu işlem orijinal DataFrame'i değiştirmez, geçici olarak yeni bir DataFrame döndürür.  
Kalıcı olarak değiştirmek için `inplace=True` parametresi eklenir:  
`df.set_index('age', inplace=True)`

Index’i tekrar varsayılan hale getirmek için ise `reset_index()` fonksiyonu kullanılabilir.  
Örneğin:  
`df.reset_index()`  
Kalıcı yapmak için yine `inplace=True` kullanılmalıdır.

In [18]:
df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [19]:
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [20]:
df.index = df.age
df.index

Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
       ...
       33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],
      dtype='float64', name='age', length=891)

In [21]:
df.drop("age", axis=1).head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [22]:
df.drop("age", axis=1, inplace=True)
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

İndexi tekrar sütuna almak için `reset_index()` fonksiyonunu kullanabilirsiniz:

```python
df.reset_index(inplace=True)
df.head()
```

In [23]:
df["age"] = df.index
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age
age,,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,22.0
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,38.0
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,26.0
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,35.0
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,35.0

## Değişkenler Üzerine İşlemler

Değişkenler üzerinde çalışmak için, DataFrame içerisindeki belirli bir sütuna erişebilir, yeni sütunlar oluşturabilir veya mevcut sütunları dönüştürebilirsiniz. 
Örneğin, bir sütuna ulaşmak için köşeli parantezler veya noktalı gösterim kullanılabilir. Ayrıca, DataFrame'e yeni bir sütun eklemek için atama operatörüyle bir liste, NumPy dizisi veya başka bir pandas serisi tanımlanabilir. Var olan sütunlar üzerinde matematiksel ya da mantıksal işlemler de rahatlıkla uygulanabilir. 

Aşağıda bazı örnekler görebilirsiniz:

```python
# Bir sütunu seçmek:
df["age"].head()

# Yeni bir sütun oluşturmak:
df["new_column"] = df["age"] * 2

# Sütunlar arasında koşullu işlem yapmak:
df["is_adult"] = df["age"] >= 18

# Bir sütunu silmek:
df = df.drop("new_column", axis=1)
```

Bu yöntemlerle, değişkenler(nam-ı diğer sütunlar) üzerinde çeşitli işlemler yaparak veri manipülasyonu gerçekleştirebilirsiniz.

In [24]:
pd.set_option('display.max_columns', None) # tüm sütunları gösterir
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:
"age" in df # age sütununun varlığını kontrol eder

True

In [26]:
df["age"].head() # age sütununun ilk 5 verisini getirir

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [27]:
type(df["age"]) # age sütununun veri tipini getirir

pandas.Series

In [28]:
df[["age"]].head() # [[]] ile sonucun DataFrame formatında çıkmasını sağlar

    age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [29]:
type(df[["age"]]) # age sütununun veri tipini getirir

pandas.DataFrame

In [30]:
df[["age", "alive"]]

      age alive
0    22.0    no
1    38.0   yes
2    26.0   yes
3    35.0   yes
4    35.0    no
..    ...   ...
886  27.0    no
887  19.0   yes
888   NaN    no
889  26.0   yes
890  32.0    no

[891 rows x 2 columns]

In [31]:
col_names = ["age", "adult_male", "alive"]
df[col_names]

      age  adult_male alive
0    22.0        True    no
1    38.0       False   yes
2    26.0       False   yes
3    35.0       False   yes
4    35.0        True    no
..    ...         ...   ...
886  27.0        True    no
887  19.0       False   yes
888   NaN       False    no
889  26.0        True   yes
890  32.0        True    no

[891 rows x 3 columns]

In [32]:
df["age2"] = df["age"] ** 2
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age2
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,729.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,361.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,676.0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1024.0

In [33]:
df["age3"] = df["age"] / df["age2"]
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age2,age3
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0,0.045455
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0,0.026316
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0,0.038462
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0,0.028571
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0,0.028571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,729.0,0.037037
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,361.0,0.052632
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,676.0,0.038462
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1024.0,0.031250

In [34]:
df.drop("age3", axis=1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age2
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0

In [36]:
df.drop(col_names , axis=1).head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,deck,embark_town,alone,age2,age3
0,0,3,male,1,0,7.2500,S,Third,man,NaN,Southampton,False,484.0,0.045455
1,1,1,female,1,0,71.2833,C,First,woman,C,Cherbourg,False,1444.0,0.026316
2,1,3,female,0,0,7.9250,S,Third,woman,NaN,Southampton,True,676.0,0.038462
3,1,1,female,1,0,53.1000,S,First,woman,C,Southampton,False,1225.0,0.028571
4,0,3,male,0,0,8.0500,S,Third,man,NaN,Southampton,True,1225.0,0.028571

In [37]:
df.loc[:, ~df.columns.str.contains("age")].head()
# 
# Açıklama:
# Bu kod, DataFrame'deki sütun adlarında "age" ifadesi geçen tüm sütunları hariç tutarak ilk 5 satırı gösterir.
# 
# - df.columns.str.contains("age"): Sütun isimlerinde "age" geçenleri True olarak işaretler.
# - ~ operatörü: True'ları False, False'ları True yapar, yani "age" içerenler dışındakiler seçilir.
# - df.loc[:, ...]: Bütün satırlardan, seçilen sütunları alırız.
# - .head(): Sonucun ilk 5 satırını gösterir.
# 
# Böylece "age" kelimesi içeren sütunlar hariç tüm sütunların ilk 5 satırını görmüş oluruz.

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## `.loc` ve `.iloc` Kullanımı

Pandas DataFrame'lerinde satır ve sütun seçimleri için iki temel özellik kullanılır: `.loc` ve `.iloc`.

### `.loc` (Etiket/İsim Bazlı Seçim)

- Satır ve sütunlara etiket (isim) ile erişim sağlar.
- Söz dizimi: `df.loc[satır_seçimi, sütun_seçimi]`
- Hem satırda hem sütunda tek bir isim, liste veya aralık kullanılabilir.
- Örnekler:
    - `df.loc[5]`: İndeksi 5 olan satırı getirir.
    - `df.loc[2:6]`: 2’den 6’ya kadar olan satırları getirir (**son değer dahil**).
    - `df.loc[:, "age"]`: Tüm satırlarda "age" sütununu getirir.
    - `df.loc[0:3, ["age", "fare"]]`: 0’dan 3’e kadar olan satırların "age" ve "fare" sütunlarını getirir.

### `.iloc` (Pozisyon/İndis Bazlı Seçim)

- Satır ve sütunlara indis (integer konumu) ile erişim sağlar.
- Söz dizimi: `df.iloc[satır_seçimi, sütun_seçimi]`
- Seçim 0 tabanlıdır; aralıklarda üst sınır **hariçtir**.
- Örnekler:
    - `df.iloc[0]`: İlk satırı getirir.
    - `df.iloc[2:5]`: 2, 3, 4. satırları getirir.
    - `df.iloc[:, 1]`: Tüm satırlarda, 2. sütunu (indis 1) getirir.
    - `df.iloc[0:3, [2, 4]]`: 0, 1, 2. satırdan; 2. ve 4. sütunları getirir.

### Temel Farklar

| Özellik               | `.loc`             | `.iloc`                  |
|-----------------------|--------------------|--------------------------|
| Erişim tipi           | Etiket/İsim        | Sayısal Pozisyon         |
| Aralık sistemi        | Son dahil          | Son hariç                |
| Hata davranışı        | Etiket yoksa hata  | Sınır dışıysa hata       |

`.loc` ve `.iloc`'u karıştırmadan, ihtiyacınıza göre veriye doğrudan erişebilirsiniz.

In [38]:
pd.set_option('display.max_columns', None)
df = sns.load_dataset('titanic')
df.iloc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [39]:
df.iloc[0,0] # 0. satırın 0. sütununu getirir

np.int64(0)

In [40]:
df.loc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False

In [41]:
df.iloc[0:3, 0:2]

   survived  pclass
0         0       3
1         1       1
2         1       3

In [42]:
df.loc[0:3, "age"]

0    22.0
1    38.0
2    26.0
3    35.0
Name: age, dtype: float64

In [43]:
col_names = ["age", "embarked", "alive"]
df.loc[0:3, col_names]

    age embarked alive
0  22.0        S    no
1  38.0        C   yes
2  26.0        S   yes
3  35.0        S   yes

Koşullu seçimler, pandas DataFrame’lerinde belirli şartları sağlayan verileri filtrelemek için kullanılır. Bir sütunda veya birden fazla sütunda koşul belirlenerek sadece bu koşulu sağlayan satırlar seçilebilir. Örneğin, bir veri çerçevesinde yaşı 30’dan büyük olan tüm kayıtları getirmek için `df[df["age"] > 30]` şeklinde bir ifade yazılır. Birden fazla şartı birleştirmek için `&` (ve) veya `|` (veya) operatörleri kullanılabilir. Örnek olarak, hem yaşı 30’dan büyük hem de cinsiyet değeri "female" olan satırları seçmek için `df[(df["age"] > 30) & (df["sex"] == "female")]` biçiminde yazılır. Tüm şartlarda, her bir koşul parantez içine alınmalıdır. Koşullu seçimler veri analizi sürecinde ilgilenilen spesifik verileri elde etmek için oldukça etkilidir.

In [44]:
df[df["age"] > 50].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False

In [ ]:
df[df["age"] > 50]["age"].count() # yaşı 50'den büyük olanların sayısını getirir

np.int64(64)

In [50]:
df.loc[df["age"] > 50, ["age", "class"]].head() # yaşı 50'den büyük olanların age ve class sütunlarını getirir

     age   class
6   54.0   First
11  58.0   First
15  55.0  Second
33  66.0  Second
54  65.0   First

In [52]:
df.loc[(df["age"]> 50) & (df["sex"] == "male"), ["age", "sex", "class"]].head() # yaşı 50'den büyük olan kadınların age, sex ve class sütunlarını getirir
# & operatörü iki koşulu birlikte sağlayan verileri getirir

     age   sex   class
6   54.0  male   First
33  66.0  male  Second
54  65.0  male   First
94  59.0  male   Third
96  71.0  male   First

In [ ]:
df.loc[
    (df['age'] > 50) & 
    (df['sex'] == "male") & 
    (df['embark_town'] == "Cherbourg"), 
    ["age", "class","embark_town"]
].head() # yaşı 50'den büyük olan kadınların Cherbourg'a yapılan yolculuklarının age, embark_town ve class sütunlarını getirir

      age  class embark_town
54   65.0  First   Cherbourg
96   71.0  First   Cherbourg
155  51.0  First   Cherbourg
174  56.0  First   Cherbourg
487  58.0  First   Cherbourg

In [55]:
df.loc[
    (df['age'] > 50) & 
    (df['sex'] == "male") & 
    (df['embark_town'] == "Cherbourg") | (df['embark_town'] == "Southampton"), 
    ["age", "class","embark_town"]
].head()

    age  class  embark_town
0  22.0  Third  Southampton
2  26.0  Third  Southampton
3  35.0  First  Southampton
4  35.0  Third  Southampton
6  54.0  First  Southampton

### Toplulaştırma (Aggregation) ve Gruplama (Grouping)

Veri analizinde, büyük veri setlerinde alt gruplar oluşturmak ve bu gruplar üzerinde toplu özet istatistikler (ortalama, toplam, adet vb.) almak oldukça önemlidir. Pandas kütüphanesinde bu işlemler oldukça pratik bir şekilde yapılabilir.

#### **Gruplama (groupby) Nedir?**
Bir DataFrame'i belirli bir sütuna göre böler ve her benzersiz kategori için ayrı birer alt tablo (grup) oluşturur. Böylece her grup üzerinde ayrı analizler ve hesaplamalar yapmak mümkün olur.

#### **Toplulaştırma (aggregation) Nedir?**
Gruplanmış alt veri kümeleri üzerinde çeşitli özet istatistikleri (ör. ortalama, toplam, adet, maksimum, minimum) hesaplamak için kullanılır.

#### **En Sık Kullanılan groupby ve aggregate Fonksiyonları**
- Eleman sayısı (`count()`)  
  Her grup içindeki elemanların sayısını verir.
- İlk değer (`first()`)  
  Her grup için ilk veriyi döndürür.
- Son değer (`last()`)  
  Her grup için son veriyi döndürür.
- Ortalama (`mean()`)  
  Sayısal değerlerin ortalamasını alır.
- Medyan (`median()`)  
  Ortanca değeri döndürür.
- En küçük değer (`min()`)  
  Her grup için minimumu döndürür.
- En büyük değer (`max()`)  
  Her grup için maksimumu döndürür.
- Standart sapma (`std()`)  
  Her grup için standart sapmayı döndürür.
- Birden fazla istatistik `agg()` ile aynı anda uygulanabilir.

Not: Yukarıdaki metotlar, pandas gruplama işlemlerinde en çok kullanılan toplulaştırma fonksiyonlarındandır.

#### **Kullanım Örnekleri**
```python
# Sınıfa göre ortalama yaş:
df.groupby("class")["age"].mean()

# Cinsiyete göre toplam bilet ücreti:
df.groupby("sex")["fare"].sum()

# Sınıf ve cinsiyete göre ortalama hayatta kalma oranı:
df.groupby(["class", "sex"])["survived"].mean()

# Sınıfa göre yaşın ortalaması ve bilet ücretinin toplamı, maksimumu:
df.groupby("class").agg({"age": "mean", "fare": ["sum", "max"]})

# Sınıfa göre yaşın ortalaması, medyanı ve standart sapması:
df.groupby("class")["age"].agg(["mean", "median", "std"])
```

#### **Neden Önemlidir?**
Gruplama ve toplulaştırma işlemleri, veri setlerinde örüntüleri, ilişkileri ve özet bilgileri hızlıca görmeyi sağlar. Analitik kararlar almak ve raporlar üretmek için güçlü ve vazgeçilmez araçlardır.

In [ ]:
df["age"].mean() # yaşın ortalamasını getirir

np.float64(29.69911764705882)

In [57]:
df.groupby("sex")["age"].mean() # cinsiyete göre yaşın ortalamasını getirir

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [ ]:
df.groupby("sex").agg({"age": "mean"}) # cinsiyete göre yaşın ortalamasını getirir

              age
sex
female  27.915709
male    30.726645

In [60]:
df.groupby("sex").agg({"age": ["mean","sum"]})

              age
             mean       sum
sex
female  27.915709   7286.00
male    30.726645  13919.17

In [61]:
df.groupby("sex").agg({"age": ["mean", "sum"],
                      "survived": "mean"})

              age            survived
             mean       sum      mean
sex
female  27.915709   7286.00  0.742038
male    30.726645  13919.17  0.188908

In [62]:
df.groupby(["sex","embark_town"]).agg({"age": ["mean"],
                                        "survived": "mean"})

                          age  survived
                         mean      mean
sex    embark_town
female Cherbourg    28.344262  0.876712
       Queenstown   24.291667  0.750000
       Southampton  27.771505  0.689655
male   Cherbourg    32.998841  0.305263
       Queenstown   30.937500  0.073171
       Southampton  30.291440  0.174603

In [64]:
df.groupby(["sex","embark_town","class"]).agg({"age": ["mean"],
                                        "survived": "mean",
                                        "sex": "count"})

                                 age  survived   sex
                                mean      mean count
sex    embark_town class
female Cherbourg   First   36.052632  0.976744    43
                   Second  19.142857  1.000000     7
                   Third   14.062500  0.652174    23
       Queenstown  First   33.000000  1.000000     1
                   Second  30.000000  1.000000     2
                   Third   22.850000  0.727273    33
       Southampton First   32.704545  0.958333    48
                   Second  29.719697  0.910448    67
                   Third   23.223684  0.375000    88
male   Cherbourg   First   40.111111  0.404762    42
                   Second  25.937500  0.200000    10
                   Third   25.016800  0.232558    43
       Queenstown  First   44.000000  0.000000     1
                   Second  57.000000  0.000000     1
                   Third   28.142857  0.076923    39
       Southampton First   41.897188  0.354430    79
                   Second  30.875889  0.154639    97
                   Third   26.574766  0.128302   265


## Pivot Table (Özet Tablo) Nedir?

Pivot table, veri kümesindeki bilgileri farklı boyutlarda özetleyerek tablo halinde gösterebilen güçlü bir araçtır. Pandas kütüphanesindeki `pivot_table` fonksiyonu ile bir DataFrame'den kolayca özet tablolar oluşturulabilir. Böylece, satır ve sütun başlıklarını istediğimiz gruplara göre ayarlayabilir ve çeşitli toplulaştırma (aggregation) fonksiyonlarını aynı anda uygulayabiliriz.

Örneğin, Titanic veri setinde yolcuların cinsiyetine, bindiği limana ve sınıfına göre ortalama yaş, hayatta kalma oranı ve yolcu sayısını özetlemek için şöyle bir pivot tablo oluşturulabilir:

```python
df.pivot_table(
    values=["age", "survived", "sex"],
    index=["sex", "embark_town", "class"],
    aggfunc={"age": "mean", "survived": "mean", "sex": "count"}
)
```

Burada:
- `values`: Hesaplanacak öznitelikleri belirtir (ör. yaş, hayatta kalma, cinsiyet sayısı)
- `index`: Satır başlıklarını belirler (ör. cinsiyet, biniş limanı, sınıf)
- `aggfunc`: Her sütunda hangi toplulaştırma fonksiyonunun uygulanacağını belirler

Sonuç olarak oluşacak tablo, satırda seçilen gruplara göre her bir grubun yaş ortalaması, hayatta kalma oranı ve toplam yolcu sayısını gösterir. Bu şekilde çok boyutlu veri analizi ve raporlama kolayca yapılabilir.

In [65]:
df.pivot_table("survived","sex","embarked")

embarked         C         Q         S
sex
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [66]:
df.pivot_table("survived","sex","embarked", aggfunc="std")

embarked         C         Q         S
sex
female    0.331042  0.439155  0.463778
male      0.462962  0.263652  0.380058

In [68]:
df.pivot_table("survived","sex",["embarked","class"])

embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First
sex
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430

embarked
class       Second     Third
sex
female    0.910448  0.375000
male      0.154639  0.128302

In [69]:
df["new_age"] = pd.cut(df["age"], [0,10,18,25,40,90])
df.head()
# pd.cut fonksiyonu, bir sütunu belirli aralıklara bölerek yeni bir sütun oluşturur. 
# Örneğin, df["age"] sütununu 0-10, 10-18, 18-25, 25-40, 40-90 aralıklarına böler ve yeni bir sütun oluşturur.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new_age
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,"(18, 25]"
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,"(25, 40]"
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,"(25, 40]"
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,"(25, 40]"
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,"(25, 40]"

In [70]:
df.pivot_table("survived","sex","new_age")

new_age   (0, 10]  (10, 18]  (18, 25]  (25, 40]  (40, 90]
sex
female   0.612903  0.729730  0.759259  0.802198  0.770833
male     0.575758  0.131579  0.120370  0.220930  0.176471

In [71]:
df.pivot_table("survived","sex", ["new_age", "class"])

new_age (0, 10]                   (10, 18]                   (18, 25]  \
class     First Second     Third     First Second     Third     First
sex
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333

new_age                      (25, 40]                      (40, 90]            \
class      Second     Third     First    Second     Third     First    Second
sex
female   0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154
male     0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238

new_age
class       Third
sex
female   0.111111
male     0.064516

### `apply` ve `lambda` Fonksiyonları

Pandas'ta `.apply()` metodu, bir DataFrame veya Series üzerindeki satırlara ya da sütunlara özel bir fonksiyonu uygulamak için kullanılır. Özellikle hızlı işlemler, dönüşümler veya karmaşık fonksiyonlar için oldukça faydalıdır.

#### Lambda Fonksiyonu
`lambda`, Python'da kısa ve isimsiz (anonim) fonksiyonlar tanımlamak için kullanılır. Genelde küçük, tek satırlık işlemler için tercih edilir.

#### Örnek Kullanım

```python
import pandas as pd

df = pd.DataFrame({
    "sayi": [1, 2, 3, 4, 5]
})

# 'sayi' sütununa, her değerin karesini alan yeni bir sütun ekleyelim:
df["karesi"] = df["sayi"].apply(lambda x: x**2)
print(df)
```

Yukarıdaki örnekte:
- `df["sayi"].apply(lambda x: x**2)` ifadesiyle, "sayi" sütunundaki her bir değere `lambda x: x**2` fonksiyonu uygulanır.
- Sonuç olarak "karesi" adında, orijinal değerlerin karesi bulunan yeni bir sütun elde edilir.

`.apply()` metodu, satır ya da sütun bazında işlem yapmak ve özelleştirilmiş fonksiyonlar tanımlamak için oldukça kullanışlıdır.

In [72]:
for col in df.columns:
    if "age" in col:
        print(col)

age
new_age

In [76]:
for col in df.columns:
    if "age" in col:
        if pd.api.types.is_numeric_dtype(df[col]):
            print((df[col]/10).head())
        else:
            print(f"{col} sütunu sayısal olmadığı için bölme işlemi uygulanamadı.")

0    2.2
1    3.8
2    2.6
3    3.5
4    3.5
Name: age, dtype: float64
new_age sütunu sayısal olmadığı için bölme işlemi uygulanamadı.

In [77]:
df["age2"] = df["age"] * 2
df["age3"] = df["age"] * 5
df[["age","age2","age3"]].apply(lambda x: x/10).head()

   age  age2  age3
0  2.2   4.4  11.0
1  3.8   7.6  19.0
2  2.6   5.2  13.0
3  3.5   7.0  17.5
4  3.5   7.0  17.5

In [79]:
df.loc[:, df.columns.str.contains("age")].select_dtypes(include="number").apply(lambda x: x/10).head()

   age  age2  age3
0  2.2   4.4  11.0
1  3.8   7.6  19.0
2  2.6   5.2  13.0
3  3.5   7.0  17.5
4  3.5   7.0  17.5

In [ ]:
# Belirli bir DataFrame'deki (df) sütun isimlerinde "age" geçen tüm sayısal sütunları seçiyoruz:
# df.columns.str.contains("age") ifadesiyle adı "age" içeren sütunlar filtreleniyor.
# select_dtypes(include="number") sadece sayısal türdeki sütunları bırakıyor.
# apply(lambda x: (x-x.mean())/x.std()) ile her sütun için z-score standartlaştırma yapılıyor; yani her değerden sütun ortalaması çıkarılıp standart sapmasına bölünüyor.
# head() ise ilk 5 satırı gösteriyor.
df.loc[:, df.columns.str.contains("age")].select_dtypes(include="number").apply(lambda x: (x-x.mean())/x.std()).head()

        age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646
3  0.364911  0.364911  0.364911
4  0.364911  0.364911  0.364911

In [82]:
def standart_scaler(col_name):
    return (col_name - col_name.mean()) / col_name.std()

df.loc[:, df.columns.str.contains("age")].select_dtypes(include="number").apply(standart_scaler).head()

        age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646
3  0.364911  0.364911  0.364911
4  0.364911  0.364911  0.364911

## Birleştirme (Merge) İşlemleri

Pandas'ta birleştirme (merge), iki veya daha fazla veri çerçevesini (DataFrame) anahtar sütunlar üzerinden bir araya getirmek için kullanılır. Farklı veri kaynaklarındaki bilgileri tek bir yapıda toplamak için çok önemli bir işlemdir.

### Temel Birleştirme Yöntemi: `pd.merge()`

İki DataFrame'i birleştirmek için `pd.merge()` fonksiyonu kullanılır. Temel kullanım şekli:

```python
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'ad': ['Ali', 'Veli', 'Ayşe', 'Fatma']
})

df2 = pd.DataFrame({
    'id': [1, 2, 5, 6],
    'puan': [95, 80, 75, 88]
})

# id sütunu üzerinden birleştirme (inner join)
birlesik_df = pd.merge(df1, df2, on='id')
```

### Birleştirme Türleri

`how` parametresiyle farklı birleştirme türleri seçilebilir:

- **inner**: Ortak olan anahtarları getirir (kesişim).
- **left**: Birinci DataFrame'in tüm satırlarını getirir, eşleşmeyenlere NaN yazar.
- **right**: İkinci DataFrame'in tüm satırlarını getirir, eşleşmeyenlere NaN yazar.
- **outer**: Tüm anahtarları getirir (birleşim).

```python
# 'left' join örneği
pd.merge(df1, df2, on='id', how='left')

# 'outer' join örneği
pd.merge(df1, df2, on='id', how='outer')
```

### Farklı Sütun İsimleriyle Birleştirme

Eğer anahtar sütunlarının isimleri farklıysa `left_on` ve `right_on` parametreleri kullanılır.

```python
df3 = pd.DataFrame({'ogrenci_id': [1, 2, 3], 'yas': [22, 21, 20]})

# df1'in 'id' sütunu ile df3'ün 'ogrenci_id' sütunu üzerinden birleştirme
pd.merge(df1, df3, left_on='id', right_on='ogrenci_id')
```

### Çoklu Sütuna Göre Birleştirme

Birden fazla sütuna göre de birleştirme yapılabilir:

```python
pd.merge(df1, df2, on=['id', 'ad'])
```

### Özet

Birleştirme işlemleriyle birden fazla veri kaynağındaki ilişkili bilgileri bir araya getirebilir, zengin ve analiz edilebilir tablolar oluşturabilirsiniz. Doğru anahtarlar ve uygun birleştirme türü seçimi, sağlıklı veri analizleri için kritik önemdedir.

In [84]:
m = np.random.randint(1, 30, size=(5, 3))
df1 = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df2 = df1 + 99
pd.concat([df1, df2]) # .concat() fonksiyonu, iki DataFrame'i birleştirmek için kullanılır.

   var1  var2  var3
0     7    23    16
1     8    11     7
2    12    29    15
3    22     1    12
4    17     2    10
0   106   122   115
1   107   110   106
2   111   128   114
3   121   100   111
4   116   101   109

In [86]:
pd.concat([df1, df2], ignore_index=True) # ignore_index=True parametresi, yeni bir index oluşturur.

   var1  var2  var3
0     7    23    16
1     8    11     7
2    12    29    15
3    22     1    12
4    17     2    10
5   106   122   115
6   107   110   106
7   111   128   114
8   121   100   111
9   116   101   109

In [88]:
df1 = pd.DataFrame({
    'employee': ['john', 'dennis', 'mark', 'maria'],
    'group': ['accounting', 'engineering', 'engineering', 'hr']
})

df2 = pd.DataFrame({
    'employee': ['mark', 'john', 'dennis', 'maria'],
    'start_date': [2010, 2009, 2014, 2019]
})

pd.merge(df1,df2)

  employee        group  start_date
0     john   accounting        2009
1   dennis  engineering        2014
2     mark  engineering        2010
3    maria           hr        2019

In [89]:
pd.merge(df1,df2, on="employee")

  employee        group  start_date
0     john   accounting        2009
1   dennis  engineering        2014
2     mark  engineering        2010
3    maria           hr        2019

In [90]:
df3 = pd.merge(df1,df2)
df4 = pd.DataFrame({
    'group': ['accounting', 'engineering', 'hr'],
    'manager': ['Caner', 'Mustafa', 'Berkcan']
})
pd.merge(df3,df4)

  employee        group  start_date  manager
0     john   accounting        2009    Caner
1   dennis  engineering        2014  Mustafa
2     mark  engineering        2010  Mustafa
3    maria           hr        2019  Berkcan