# Pandas Alıştırmalar

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

Görev 1: Seaborn kütüphanesi içerisinden Titanic veri setini tanımlayınız.

In [2]:
df = sns.load_dataset("titanic")

Görev 2: Yukarıda tanımlanan Titanic veri setindeki kadın ve erkek yolcuların sayısını bulunuz.

In [3]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

Görev 3: Her bir sutuna ait unique değerlerin sayısını bulunuz.

In [4]:
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

Görev 4: pclass değişkeninin unique değerleri bulunuz.

In [5]:
df["pclass"].unique()

array([3, 1, 2])

Görev 5: pclass ve parch değişkenlerinin unique değerlerinin sayısını bulunuz.

In [6]:
df[["pclass", "parch"]].nunique()

pclass    3
parch     7
dtype: int64

Görev 6: embarked değişkeninin tipini kontrol ediniz. Tipini category olarak değiştiriniz. Tekrar tipini kontrol ediniz.

In [8]:
df["embarked"].dtype

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False, categories_dtype=str)

In [9]:
df["embarked"] = df["embarked"].astype("category")
df["embarked"].dtype

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False, categories_dtype=str)

Görev 7: embarked değeri C olanların tüm bilgelerini gösteriniz.

In [10]:
df[df["embarked"] == "C"]

     survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck embark_town alive  alone
1           1       1  female  38.00      1      0   71.2833        C   First  woman       False    C   Cherbourg   yes  False
9           1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN   Cherbourg   yes  False
19          1       3  female    NaN      0      0    7.2250        C   Third  woman       False  NaN   Cherbourg   yes   True
26          0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
30          0       1    male  40.00      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
31          1       1  female    NaN      1      0  146.5208        C   First  woman       False    B   Cherbourg   yes  False
34          0       1    male  28.00      1      0   82.1708        C   First    man        True  NaN   Cherbourg    no  False
36          1       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg   yes   True
39          1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
42          0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
43          1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN   Cherbourg   yes  False
48          0       3    male    NaN      2      0   21.6792        C   Third    man        True  NaN   Cherbourg    no  False
52          1       1  female  49.00      1      0   76.7292        C   First  woman       False    D   Cherbourg   yes  False
54          0       1    male  65.00      0      1   61.9792        C   First    man        True    B   Cherbourg    no  False
57          0       3    male  28.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
60          0       3    male  22.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
64          0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
65          1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN   Cherbourg   yes  False
73          0       3    male  26.00      1      0   14.4542        C   Third    man        True  NaN   Cherbourg    no  False
96          0       1    male  71.00      0      0   34.6542        C   First    man        True    A   Cherbourg    no   True
97          1       1    male  23.00      0      1   63.3583        C   First    man        True    D   Cherbourg   yes  False
111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN   Cherbourg    no  False
114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN   Cherbourg    no   True
118         0       1    male  24.00      0      1  247.5208        C   First    man        True    B   Cherbourg    no  False
122         0       2    male  32.50      1      0   30.0708        C  Second    man        True  NaN   Cherbourg    no  False
125         1       3    male  12.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
128         1       3  female    NaN      1      1   22.3583        C   Third  woman       False    F   Cherbourg   yes  False
130         0       3    male  33.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
135         0       2    male  23.00      0      0   15.0458        C  Second    man        True  NaN   Cherbourg    no   True
139         0       1    male  24.00      0      0   79.2000        C   First    man        True    B   Cherbourg    no   True
140         0       3  female    NaN      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg    no  False
155         0       1    male  51.00      0      1   61.3792        C   First    man        True  NaN   Cherbourg    no  False
174         0       1    male  56.00      0      0   30.6958        C   First    man        True    A   Cherbourg    no   True
177         0       1  female  50.00      0      0   28.7125        C   First  woman       False    C   Cherbourg    no   True
181         0       2    male    NaN      0      0   15.0500        C  Second    man        True  NaN   Cherbourg    no   True
194         1       1  female  44.00      0      0   27.7208        C   First  woman       False    B   Cherbourg   yes   True
195         1       1  female  58.00      0      0  146.5208        C   First  woman       False    B   Cherbourg   yes   True
203         0       3    male  45.50      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
207         1       3    male  26.00      0      0   18.7875        C   Third    man        True  NaN   Cherbourg   yes   True
209         1       1    male  40.00      0      0   31.0000        C   First    man        True    A   Cherbourg   yes   True
215         1       1  female  31.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
218         1       1  female  32.00      0      0   76.2917        C   First  woman       False    D   Cherbourg   yes   True
240         0       3  female    NaN      1      0   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
244         0       3    male  30.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
255         1       3  female  29.00      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg   yes  False
256         1       1  female    NaN      0      0   79.2000        C   First  woman       False  NaN   Cherbourg   yes   True
258         1       1  female  35.00      0      0  512.3292        C   First  woman       False  NaN   Cherbourg   yes   True
273         0       1    male  37.00      0      1   29.7000        C   First    man        True    C   Cherbourg    no  False
285         0       3    male  33.00      0      0    8.6625        C   Third    man        True  NaN   Cherbourg    no   True
291         1       1  female  19.00      1      0   91.0792        C   First  woman       False    B   Cherbourg   yes  False
292         0       2    male  36.00      0      0   12.8750        C  Second    man        True    D   Cherbourg    no   True
295         0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
296         0       3    male  23.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
299         1       1  female  50.00      0      1  247.5208        C   First  woman       False    B   Cherbourg   yes  False
306         1       1  female    NaN      0      0  110.8833        C   First  woman       False  NaN   Cherbourg   yes   True
307         1       1  female  17.00      1      0  108.9000        C   First  woman       False    C   Cherbourg   yes  False
308         0       2    male  30.00      1      0   24.0000        C  Second    man        True  NaN   Cherbourg    no  False
309         1       1  female  30.00      0      0   56.9292        C   First  woman       False    E   Cherbourg   yes   True
310         1       1  female  24.00      0      0   83.1583        C   First  woman       False    C   Cherbourg   yes   True
311         1       1  female  18.00      2      2  262.3750        C   First  woman       False    B   Cherbourg   yes  False
319         1       1  female  40.00      1      1  134.5000        C   First  woman       False    E   Cherbourg   yes  False
325         1       1  female  36.00      0      0  135.6333        C   First  woman       False    C   Cherbourg   yes   True
329         1       1  female  16.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
337         1       1  female  41.00      0      0  134.5000        C   First  woman       False    E   Cherbourg   yes   True
352         0       3    male  15.00      1      1    7.2292        C   Third  child       False  NaN   Cherbourg    no  False
354         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
361         0       2    male  29.00      1      0   27.7208        C  Second    man        True  NaN   Cherbourg    no  False
362         0       3  female  45.00      0      1   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
366         1       1  female  60.00      1      0   75.2500        C   First  woman       False    D   Cherbourg   yes  False
367         1       3  female    NaN      0      0    7.2292        C   Third  woman       False  NaN   Cherbourg   yes   True
369         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B   Cherbourg   yes   True
370         1       1    male  25.00      1      0   55.4417        C   First    man        True    E   Cherbourg   yes  False
373         0       1    male  22.00      0      0  135.6333        C   First    man        True  NaN   Cherbourg    no   True
375         1       1  female    NaN      1      0   82.1708        C   First  woman       False  NaN   Cherbourg   yes  False
377         0       1    male  27.00      0      2  211.5000        C   First    man        True    C   Cherbourg    no  False
378         0       3    male  20.00      0      0    4.0125        C   Third    man        True  NaN   Cherbourg    no   True
380         1       1  female  42.00      0      0  227.5250        C   First  woman       False  NaN   Cherbourg   yes   True
381         1       3  female   1.00      0      2   15.7417        C   Third  child       False  NaN   Cherbourg   yes  False
389         1       2  female  17.00      0      0   12.0000        C  Second  woman       False  NaN   Cherbourg   yes   True
393         1       1  female  23.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
420         0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
448         1       3  female   5.00      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
452         0       1    male  30.00      0      0   27.7500        C   First    man        True    C   Cherbourg    no   True
453         1       1    male  49.00      1      0   89.1042        C   First    man        True    C   Cherbourg   yes  False
455         1       3    male  29.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg   yes   True
469         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
473         1       2  female  23.00      0      0   13.7917        C  Second  woman       False    D   Cherbourg   yes   True
484         1       1    male  25.00      1      0   91.0792        C   First    man        True    B   Cherbourg   yes  False
487         0       1    male  58.00      0      0   29.7000        C   First    man        True    B   Cherbourg    no   True
493         0       1    male  71.00      0      0   49.5042        C   First    man        True  NaN   Cherbourg    no   True
495         0       3    male    NaN      0      0   14.4583        C   Third    man        True  NaN   Cherbourg    no   True
496         1       1  female  54.00      1      0   78.2667        C   First  woman       False    D   Cherbourg   yes  False
505         0       1    male  18.00      1      0  108.9000        C   First    man        True    C   Cherbourg    no  False
513         1       1  female  54.00      1      0   59.4000        C   First  woman       False  NaN   Cherbourg   yes  False
522         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
523         1       1  female  44.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
524         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
531         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
532         0       3    male  17.00      1      1    7.2292        C   Third    man        True  NaN   Cherbourg    no  False
533         1       3  female    NaN      0      2   22.3583        C   Third  woman       False  NaN   Cherbourg   yes  False
537         1       1  female  30.00      0      0  106.4250        C   First  woman       False  NaN   Cherbourg   yes   True
539         1       1  female  22.00      0      2   49.5000        C   First  woman       False    B   Cherbourg   yes  False
544         0       1    male  50.00      1      0  106.4250        C   First    man        True    C   Cherbourg    no  False
547         1       2    male    NaN      0      0   13.8625        C  Second    man        True  NaN   Cherbourg   yes   True
550         1       1    male  17.00      0      2  110.8833        C   First    man        True    C   Cherbourg   yes  False
553         1       3    male  22.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg   yes   True
556         1       1  female  48.00      1      0   39.6000        C   First  woman       False    A   Cherbourg   yes  False
557         0       1    male    NaN      0      0  227.5250        C   First    man        True  NaN   Cherbourg    no   True
568         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
578         0       3  female    NaN      1      0   14.4583        C   Third  woman       False  NaN   Cherbourg    no  False
581         1       1  female  39.00      1      1  110.8833        C   First  woman       False    C   Cherbourg   yes  False
583         0       1    male  36.00      0      0   40.1250        C   First    man        True    A   Cherbourg    no   True
584         0       3    male    NaN      0      0    8.7125        C   Third    man        True  NaN   Cherbourg    no   True
587         1       1    male  60.00      1      1   79.2000        C   First    man        True    B   Cherbourg   yes  False
591         1       1  female  52.00      1      0   78.2667        C   First  woman       False    D   Cherbourg   yes  False
598         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
599         1       1    male  49.00      1      0   56.9292        C   First    man        True    A   Cherbourg   yes  False
604         1       1    male  35.00      0      0   26.5500        C   First    man        True  NaN   Cherbourg   yes   True
608         1       2  female  22.00      1      2   41.5792        C  Second  woman       False  NaN   Cherbourg   yes  False
620         0       3    male  27.00      1      0   14.4542        C   Third    man        True  NaN   Cherbourg    no  False
622         1       3    male  20.00      1      1   15.7417        C   Third    man        True  NaN   Cherbourg   yes  False
632         1       1    male  32.00      0      0   30.5000        C   First    man        True    B   Cherbourg   yes   True
641         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B   Cherbourg   yes   True
644         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
645         1       1    male  48.00      1      0   76.7292        C   First    man        True    D   Cherbourg   yes  False
647         1       1    male  56.00      0      0   35.5000        C   First    man        True    A   Cherbourg   yes   True
659         0       1    male  58.00      0      2  113.2750        C   First    man        True    D   Cherbourg    no  False
661         0       3    male  40.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
679         1       1    male  36.00      0      1  512.3292        C   First    man        True    B   Cherbourg   yes  False
681         1       1    male  27.00      0      0   76.7292        C   First    man        True    D   Cherbourg   yes   True
685         0       2    male  25.00      1      2   41.5792        C  Second    man        True  NaN   Cherbourg    no  False
691         1       3  female   4.00      0      1   13.4167        C   Third  child       False  NaN   Cherbourg   yes  False
693         0       3    male  25.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
698         0       1    male  49.00      1      1  110.8833        C   First    man        True    C   Cherbourg    no  False
700         1       1  female  18.00      1      0  227.5250        C   First  woman       False    C   Cherbourg   yes  False
702         0       3  female  18.00      0      1   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
709         1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN   Cherbourg   yes  False
710         1       1  female  24.00      0      0   49.5042        C   First  woman       False    C   Cherbourg   yes   True
716         1       1  female  38.00      0      0  227.5250        C   First  woman       False    C   Cherbourg   yes   True
731         0       3    male  11.00      0      0   18.7875        C   Third  child       False  NaN   Cherbourg    no   True
737         1       1    male  35.00      0      0  512.3292        C   First    man        True    B   Cherbourg   yes   True
742         1       1  female  21.00      2      2  262.3750        C   First  woman       False    B   Cherbourg   yes  False
762         1       3    male  20.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg   yes   True
766         0       1    male    NaN      0      0   39.6000        C   First    man        True  NaN   Cherbourg    no   True
773         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
780         1       3  female  13.00      0      0    7.2292        C   Third  child       False  NaN   Cherbourg   yes   True
789         0       1    male  46.00      0      0   79.2000        C   First    man        True    B   Cherbourg    no   True
793         0       1    male    NaN      0      0   30.6958        C   First    man        True  NaN   Cherbourg    no   True
798         0       3    male  30.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
803         1       3    male   0.42      0      1    8.5167        C   Third  child       False  NaN   Cherbourg   yes  False
817         0       2    male  31.00      1      1   37.0042        C  Second    man        True  NaN   Cherbourg    no  False
827         1       2    male   1.00      0      2   37.0042        C  Second  child       False  NaN   Cherbourg   yes  False
830         1       3  female  15.00      1      0   14.4542        C   Third  child       False  NaN   Cherbourg   yes  False
832         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
835         1       1  female  39.00      1      1   83.1583        C   First  woman       False    E   Cherbourg   yes  False
839         1       1    male    NaN      0      0   29.7000        C   First    man        True    C   Cherbourg   yes   True

Görev 8: embarked değeri S olmayanların tüm bilgelerini gösteriniz.

In [11]:
df[df["embarked"] != "S"]

     survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck embark_town alive  alone
1           1       1  female  38.00      1      0   71.2833        C   First  woman       False    C   Cherbourg   yes  False
5           0       3    male    NaN      0      0    8.4583        Q   Third    man        True  NaN  Queenstown    no   True
9           1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN   Cherbourg   yes  False
16          0       3    male   2.00      4      1   29.1250        Q   Third  child       False  NaN  Queenstown    no  False
19          1       3  female    NaN      0      0    7.2250        C   Third  woman       False  NaN   Cherbourg   yes   True
22          1       3  female  15.00      0      0    8.0292        Q   Third  child       False  NaN  Queenstown   yes   True
26          0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
28          1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
30          0       1    male  40.00      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
31          1       1  female    NaN      1      0  146.5208        C   First  woman       False    B   Cherbourg   yes  False
32          1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
34          0       1    male  28.00      1      0   82.1708        C   First    man        True  NaN   Cherbourg    no  False
36          1       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg   yes   True
39          1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
42          0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
43          1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN   Cherbourg   yes  False
44          1       3  female  19.00      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
46          0       3    male    NaN      1      0   15.5000        Q   Third    man        True  NaN  Queenstown    no  False
47          1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
48          0       3    male    NaN      2      0   21.6792        C   Third    man        True  NaN   Cherbourg    no  False
52          1       1  female  49.00      1      0   76.7292        C   First  woman       False    D   Cherbourg   yes  False
54          0       1    male  65.00      0      1   61.9792        C   First    man        True    B   Cherbourg    no  False
57          0       3    male  28.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
60          0       3    male  22.00      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
61          1       1  female  38.00      0      0   80.0000      NaN   First  woman       False    B         NaN   yes   True
64          0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
65          1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN   Cherbourg   yes  False
73          0       3    male  26.00      1      0   14.4542        C   Third    man        True  NaN   Cherbourg    no  False
82          1       3  female    NaN      0      0    7.7875        Q   Third  woman       False  NaN  Queenstown   yes   True
96          0       1    male  71.00      0      0   34.6542        C   First    man        True    A   Cherbourg    no   True
97          1       1    male  23.00      0      1   63.3583        C   First    man        True    D   Cherbourg   yes  False
109         1       3  female    NaN      1      0   24.1500        Q   Third  woman       False  NaN  Queenstown   yes  False
111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN   Cherbourg    no  False
114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN   Cherbourg    no   True
116         0       3    male  70.50      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
118         0       1    male  24.00      0      1  247.5208        C   First    man        True    B   Cherbourg    no  False
122         0       2    male  32.50      1      0   30.0708        C  Second    man        True  NaN   Cherbourg    no  False
125         1       3    male  12.00      1      0   11.2417        C   Third  child       False  NaN   Cherbourg   yes  False
126         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
128         1       3  female    NaN      1      1   22.3583        C   Third  woman       False    F   Cherbourg   yes  False
130         0       3    male  33.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
135         0       2    male  23.00      0      0   15.0458        C  Second    man        True  NaN   Cherbourg    no   True
139         0       1    male  24.00      0      0   79.2000        C   First    man        True    B   Cherbourg    no   True
140         0       3  female    NaN      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg    no  False
143         0       3    male  19.00      0      0    6.7500        Q   Third    man        True  NaN  Queenstown    no   True
155         0       1    male  51.00      0      1   61.3792        C   First    man        True  NaN   Cherbourg    no  False
156         1       3  female  16.00      0      0    7.7333        Q   Third  woman       False  NaN  Queenstown   yes   True
171         0       3    male   4.00      4      1   29.1250        Q   Third  child       False  NaN  Queenstown    no  False
174         0       1    male  56.00      0      0   30.6958        C   First    man        True    A   Cherbourg    no   True
177         0       1  female  50.00      0      0   28.7125        C   First  woman       False    C   Cherbourg    no   True
181         0       2    male    NaN      0      0   15.0500        C  Second    man        True  NaN   Cherbourg    no   True
186         1       3  female    NaN      1      0   15.5000        Q   Third  woman       False  NaN  Queenstown   yes  False
188         0       3    male  40.00      1      1   15.5000        Q   Third    man        True  NaN  Queenstown    no  False
194         1       1  female  44.00      0      0   27.7208        C   First  woman       False    B   Cherbourg   yes   True
195         1       1  female  58.00      0      0  146.5208        C   First  woman       False    B   Cherbourg   yes   True
196         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
198         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
203         0       3    male  45.50      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
207         1       3    male  26.00      0      0   18.7875        C   Third    man        True  NaN   Cherbourg   yes   True
208         1       3  female  16.00      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
209         1       1    male  40.00      0      0   31.0000        C   First    man        True    A   Cherbourg   yes   True
214         0       3    male    NaN      1      0    7.7500        Q   Third    man        True  NaN  Queenstown    no  False
215         1       1  female  31.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
218         1       1  female  32.00      0      0   76.2917        C   First  woman       False    D   Cherbourg   yes   True
240         0       3  female    NaN      1      0   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
241         1       3  female    NaN      1      0   15.5000        Q   Third  woman       False  NaN  Queenstown   yes  False
244         0       3    male  30.00      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
245         0       1    male  44.00      2      0   90.0000        Q   First    man        True    C  Queenstown    no  False
255         1       3  female  29.00      0      2   15.2458        C   Third  woman       False  NaN   Cherbourg   yes  False
256         1       1  female    NaN      0      0   79.2000        C   First  woman       False  NaN   Cherbourg   yes   True
258         1       1  female  35.00      0      0  512.3292        C   First  woman       False  NaN   Cherbourg   yes   True
260         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
264         0       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown    no   True
273         0       1    male  37.00      0      1   29.7000        C   First    man        True    C   Cherbourg    no  False
274         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
278         0       3    male   7.00      4      1   29.1250        Q   Third  child       False  NaN  Queenstown    no  False
280         0       3    male  65.00      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
285         0       3    male  33.00      0      0    8.6625        C   Third    man        True  NaN   Cherbourg    no   True
289         1       3  female  22.00      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
291         1       1  female  19.00      1      0   91.0792        C   First  woman       False    B   Cherbourg   yes  False
292         0       2    male  36.00      0      0   12.8750        C  Second    man        True    D   Cherbourg    no   True
295         0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN   Cherbourg    no   True
296         0       3    male  23.50      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
299         1       1  female  50.00      0      1  247.5208        C   First  woman       False    B   Cherbourg   yes  False
300         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
301         1       3    male    NaN      2      0   23.2500        Q   Third    man        True  NaN  Queenstown   yes  False
303         1       2  female    NaN      0      0   12.3500        Q  Second  woman       False    E  Queenstown   yes   True
306         1       1  female    NaN      0      0  110.8833        C   First  woman       False  NaN   Cherbourg   yes   True
307         1       1  female  17.00      1      0  108.9000        C   First  woman       False    C   Cherbourg   yes  False
308         0       2    male  30.00      1      0   24.0000        C  Second    man        True  NaN   Cherbourg    no  False
309         1       1  female  30.00      0      0   56.9292        C   First  woman       False    E   Cherbourg   yes   True
310         1       1  female  24.00      0      0   83.1583        C   First  woman       False    C   Cherbourg   yes   True
311         1       1  female  18.00      2      2  262.3750        C   First  woman       False    B   Cherbourg   yes  False
319         1       1  female  40.00      1      1  134.5000        C   First  woman       False    E   Cherbourg   yes  False
322         1       2  female  30.00      0      0   12.3500        Q  Second  woman       False  NaN  Queenstown   yes   True
325         1       1  female  36.00      0      0  135.6333        C   First  woman       False    C   Cherbourg   yes   True
329         1       1  female  16.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
330         1       3  female    NaN      2      0   23.2500        Q   Third  woman       False  NaN  Queenstown   yes  False
337         1       1  female  41.00      0      0  134.5000        C   First  woman       False    E   Cherbourg   yes   True
352         0       3    male  15.00      1      1    7.2292        C   Third  child       False  NaN   Cherbourg    no  False
354         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
358         1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
359         1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN  Queenstown   yes   True
361         0       2    male  29.00      1      0   27.7208        C  Second    man        True  NaN   Cherbourg    no  False
362         0       3  female  45.00      0      1   14.4542        C   Third  woman       False  NaN   Cherbourg    no  False
364         0       3    male    NaN      1      0   15.5000        Q   Third    man        True  NaN  Queenstown    no  False
366         1       1  female  60.00      1      0   75.2500        C   First  woman       False    D   Cherbourg   yes  False
367         1       3  female    NaN      0      0    7.2292        C   Third  woman       False  NaN   Cherbourg   yes   True
368         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown   yes   True
369         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B   Cherbourg   yes   True
370         1       1    male  25.00      1      0   55.4417        C   First    man        True    E   Cherbourg   yes  False
373         0       1    male  22.00      0      0  135.6333        C   First    man        True  NaN   Cherbourg    no   True
375         1       1  female    NaN      1      0   82.1708        C   First  woman       False  NaN   Cherbourg   yes  False
377         0       1    male  27.00      0      2  211.5000        C   First    man        True    C   Cherbourg    no  False
378         0       3    male  20.00      0      0    4.0125        C   Third    man        True  NaN   Cherbourg    no   True
380         1       1  female  42.00      0      0  227.5250        C   First  woman       False  NaN   Cherbourg   yes   True
381         1       3  female   1.00      0      2   15.7417        C   Third  child       False  NaN   Cherbourg   yes  False
388         0       3    male    NaN      0      0    7.7292        Q   Third    man        True  NaN  Queenstown    no   True
389         1       2  female  17.00      0      0   12.0000        C  Second  woman       False  NaN   Cherbourg   yes   True
393         1       1  female  23.00      1      0  113.2750        C   First  woman       False    D   Cherbourg   yes  False
411         0       3    male    NaN      0      0    6.8583        Q   Third    man        True  NaN  Queenstown    no   True
412         1       1  female  33.00      1      0   90.0000        Q   First  woman       False    C  Queenstown   yes  False
420         0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN   Cherbourg    no   True
421         0       3    male  21.00      0      0    7.7333        Q   Third    man        True  NaN  Queenstown    no   True
428         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
448         1       3  female   5.00      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
452         0       1    male  30.00      0      0   27.7500        C   First    man        True    C   Cherbourg    no   True
453         1       1    male  49.00      1      0   89.1042        C   First    man        True    C   Cherbourg   yes  False
455         1       3    male  29.00      0      0    7.8958        C   Third    man        True  NaN   Cherbourg   yes   True
459         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
468         0       3    male    NaN      0      0    7.7250        Q   Third    man        True  NaN  Queenstown    no   True
469         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN   Cherbourg   yes  False
473         1       2  female  23.00      0      0   13.7917        C  Second  woman       False    D   Cherbourg   yes   True
484         1       1    male  25.00      1      0   91.0792        C   First    man        True    B   Cherbourg   yes  False
487         0       1    male  58.00      0      0   29.7000        C   First    man        True    B   Cherbourg    no   True
493         0       1    male  71.00      0      0   49.5042        C   First    man        True  NaN   Cherbourg    no   True
495         0       3    male    NaN      0      0   14.4583        C   Third    man        True  NaN   Cherbourg    no   True
496         1       1  female  54.00      1      0   78.2667        C   First  woman       False    D   Cherbourg   yes  False
501         0       3  female  21.00      0      0    7.7500        Q   Third  woman       False  NaN  Queenstown    no   True
502         0       3  female    NaN      0      0    7.6292        Q   Third  woman       False  NaN  Queenstown    no   True
505         0       1    male  18.00      1      0  108.9000        C   First    man        True    C   Cherbourg    no  False
510         1       3    male  29.00      0      0    7.7500        Q   Third    man        True  NaN  Queenstown   yes   True
513         1       1  female  54.00      1      0   59.4000        C   First  woman       False  NaN   Cherbourg   yes  False
517         0       3    male    NaN      0      0   24.1500        Q   Third    man        True  NaN  Queenstown    no   True
522         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN   Cherbourg    no   True
523         1       1  female  44.00      0      1   57.9792        C   First  woman       False    B   Cherbourg   yes  False
524         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
525         0       3    male  40.50      0      0    7.7500        Q   Third    man        True  NaN  Queenstown    no   True
531         0       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN   Cherbourg    no   True
532         0       3    male  17.00      1      1    7.2292        C   Third    man        True  NaN   Cherbourg    no  False
533         1       3  female    NaN      0      2   22.3583        C   Third  woman       False  NaN   Cherbourg   yes  False
537         1       1  female  30.00      0      0  106.4250        C   First  woman       False  NaN   Cherbourg   yes   True
539         1       1  female  22.00      0      2   49.5000        C   First  woman       False    B   Cherbourg   yes  False
544         0       1    male  50.00      1      0  106.4250        C   First    man        True    C   Cherbourg    no  False
547         1       2    male    NaN      0      0   13.8625        C  Second    man        True  NaN   Cherbourg   yes   True
550         1       1    male  17.00      0      2  110.8833        C   First    man        True    C   Cherbourg   yes  False

Görev 9: Yaşı 30 dan küçük ve kadın olan yolcuların tüm bilgilerini gösteriniz.

In [12]:
df[(df["age"] < 30) & (df["sex"] == "female")]

     survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck  embark_town alive  alone
2           1       3  female  26.00      0      0    7.9250        S   Third  woman       False  NaN  Southampton   yes   True
8           1       3  female  27.00      0      2   11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9           1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN    Cherbourg   yes  False
10          1       3  female   4.00      1      1   16.7000        S   Third  child       False    G  Southampton   yes  False
14          0       3  female  14.00      0      0    7.8542        S   Third  child       False  NaN  Southampton    no   True
22          1       3  female  15.00      0      0    8.0292        Q   Third  child       False  NaN   Queenstown   yes   True
24          0       3  female   8.00      3      1   21.0750        S   Third  child       False  NaN  Southampton    no  False
38          0       3  female  18.00      2      0   18.0000        S   Third  woman       False  NaN  Southampton    no  False
39          1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN    Cherbourg   yes  False
41          0       2  female  27.00      1      0   21.0000        S  Second  woman       False  NaN  Southampton    no  False
43          1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN    Cherbourg   yes  False
44          1       3  female  19.00      0      0    7.8792        Q   Third  woman       False  NaN   Queenstown   yes   True
49          0       3  female  18.00      1      0   17.8000        S   Third  woman       False  NaN  Southampton    no  False
53          1       2  female  29.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
56          1       2  female  21.00      0      0   10.5000        S  Second  woman       False  NaN  Southampton   yes   True
58          1       2  female   5.00      1      2   27.7500        S  Second  child       False  NaN  Southampton   yes  False
66          1       2  female  29.00      0      0   10.5000        S  Second  woman       False    F  Southampton   yes   True
68          1       3  female  17.00      4      2    7.9250        S   Third  woman       False  NaN  Southampton   yes  False
71          0       3  female  16.00      5      2   46.9000        S   Third  woman       False  NaN  Southampton    no  False
84          1       2  female  17.00      0      0   10.5000        S  Second  woman       False  NaN  Southampton   yes   True
88          1       1  female  23.00      3      2  263.0000        S   First  woman       False    C  Southampton   yes  False
100         0       3  female  28.00      0      0    7.8958        S   Third  woman       False  NaN  Southampton    no   True
106         1       3  female  21.00      0      0    7.6500        S   Third  woman       False  NaN  Southampton   yes   True
111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN    Cherbourg    no  False
113         0       3  female  20.00      1      0    9.8250        S   Third  woman       False  NaN  Southampton    no  False
114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN    Cherbourg    no   True
119         0       3  female   2.00      4      2   31.2750        S   Third  child       False  NaN  Southampton    no  False
133         1       2  female  29.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
136         1       1  female  19.00      0      2   26.2833        S   First  woman       False    D  Southampton   yes  False
141         1       3  female  22.00      0      0    7.7500        S   Third  woman       False  NaN  Southampton   yes   True
142         1       3  female  24.00      1      0   15.8500        S   Third  woman       False  NaN  Southampton   yes  False
147         0       3  female   9.00      2      2   34.3750        S   Third  child       False  NaN  Southampton    no  False
151         1       1  female  22.00      1      0   66.6000        S   First  woman       False    C  Southampton   yes  False
156         1       3  female  16.00      0      0    7.7333        Q   Third  woman       False  NaN   Queenstown   yes   True
172         1       3  female   1.00      1      1   11.1333        S   Third  child       False  NaN  Southampton   yes  False
184         1       3  female   4.00      0      2   22.0250        S   Third  child       False  NaN  Southampton   yes  False
192         1       3  female  19.00      1      0    7.8542        S   Third  woman       False  NaN  Southampton   yes  False
199         0       2  female  24.00      0      0   13.0000        S  Second  woman       False  NaN  Southampton    no   True
205         0       3  female   2.00      0      1   10.4625        S   Third  child       False    G  Southampton    no  False
208         1       3  female  16.00      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown   yes   True
216         1       3  female  27.00      0      0    7.9250        S   Third  woman       False  NaN  Southampton   yes   True
233         1       3  female   5.00      4      2   31.3875        S   Third  child       False  NaN  Southampton   yes  False
237         1       2  female   8.00      0      2   26.2500        S  Second  child       False  NaN  Southampton   yes  False
246         0       3  female  25.00      0      0    7.7750        S   Third  woman       False  NaN  Southampton    no   True
247         1       2  female  24.00      0      2   14.5000        S  Second  woman       False  NaN  Southampton   yes  False
251         0       3  female  29.00      1      1   10.4625        S   Third  woman       False    G  Southampton    no  False
255         1       3  female  29.00      0      2   15.2458        C   Third  woman       False  NaN    Cherbourg   yes  False
289         1       3  female  22.00      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown   yes   True
290         1       1  female  26.00      0      0   78.8500        S   First  woman       False  NaN  Southampton   yes   True
291         1       1  female  19.00      1      0   91.0792        C   First  woman       False    B    Cherbourg   yes  False
293         0       3  female  24.00      0      0    8.8500        S   Third  woman       False  NaN  Southampton    no   True
297         0       1  female   2.00      1      2  151.5500        S   First  child       False    C  Southampton    no  False
307         1       1  female  17.00      1      0  108.9000        C   First  woman       False    C    Cherbourg   yes  False
310         1       1  female  24.00      0      0   83.1583        C   First  woman       False    C    Cherbourg   yes   True
311         1       1  female  18.00      2      2  262.3750        C   First  woman       False    B    Cherbourg   yes  False
312         0       2  female  26.00      1      1   26.0000        S  Second  woman       False  NaN  Southampton    no  False
315         1       3  female  26.00      0      0    7.8542        S   Third  woman       False  NaN  Southampton   yes   True
316         1       2  female  24.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
323         1       2  female  22.00      1      1   29.0000        S  Second  woman       False  NaN  Southampton   yes  False
329         1       1  female  16.00      0      1   57.9792        C   First  woman       False    B    Cherbourg   yes  False
341         1       1  female  24.00      3      2  263.0000        S   First  woman       False    C  Southampton   yes  False
345         1       2  female  24.00      0      0   13.0000        S  Second  woman       False    F  Southampton   yes   True
356         1       1  female  22.00      0      1   55.0000        S   First  woman       False    E  Southampton   yes  False
369         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B    Cherbourg   yes   True
374         0       3  female   3.00      3      1   21.0750        S   Third  child       False  NaN  Southampton    no  False
376         1       3  female  22.00      0      0    7.2500        S   Third  woman       False  NaN  Southampton   yes   True
381         1       3  female   1.00      0      2   15.7417        C   Third  child       False  NaN    Cherbourg   yes  False
389         1       2  female  17.00      0      0   12.0000        C  Second  woman       False  NaN    Cherbourg   yes   True
393         1       1  female  23.00      1      0  113.2750        C   First  woman       False    D    Cherbourg   yes  False
394         1       3  female  24.00      0      2   16.7000        S   Third  woman       False    G  Southampton   yes  False
399         1       2  female  28.00      0      0   12.6500        S  Second  woman       False  NaN  Southampton   yes   True
402         0       3  female  21.00      1      0    9.8250        S   Third  woman       False  NaN  Southampton    no  False
404         0       3  female  20.00      0      0    8.6625        S   Third  woman       False  NaN  Southampton    no   True
417         1       2  female  18.00      0      2   13.0000        S  Second  woman       False  NaN  Southampton   yes  False
419         0       3  female  10.00      0      2   24.1500        S   Third  child       False  NaN  Southampton    no  False
423         0       3  female  28.00      1      1   14.4000        S   Third  woman       False  NaN  Southampton    no  False
426         1       2  female  28.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
427         1       2  female  19.00      0      0   26.0000        S  Second  woman       False  NaN  Southampton   yes   True
435         1       1  female  14.00      1      2  120.0000        S   First  child       False    B  Southampton   yes  False
436         0       3  female  21.00      2      2   34.3750        S   Third  woman       False  NaN  Southampton    no  False
437         1       2  female  24.00      2      3   18.7500        S  Second  woman       False  NaN  Southampton   yes  False
443         1       2  female  28.00      0      0   13.0000        S  Second  woman       False  NaN  Southampton   yes   True
446         1       2  female  13.00      0      1   19.5000        S  Second  child       False  NaN  Southampton   yes  False
448         1       3  female   5.00      2      1   19.2583        C   Third  child       False  NaN    Cherbourg   yes  False
469         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN    Cherbourg   yes  False
473         1       2  female  23.00      0      0   13.7917        C  Second  woman       False    D    Cherbourg   yes   True
474         0       3  female  22.00      0      0    9.8375        S   Third  woman       False  NaN  Southampton    no   True
479         1       3  female   2.00      0      1   12.2875        S   Third  child       False  NaN  Southampton   yes  False
498         0       1  female  25.00      1      2  151.5500        S   First  woman       False    C  Southampton    no  False
501         0       3  female  21.00      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown    no   True
504         1       1  female  16.00      0      0   86.5000        S   First  woman       False    B  Southampton   yes   True
530         1       2  female   2.00      1      1   26.0000        S  Second  child       False  NaN  Southampton   yes  False
535         1       2  female   7.00      0      2   26.2500        S  Second  child       False  NaN  Southampton   yes  False
539         1       1  female  22.00      0      2   49.5000        C   First  woman       False    B    Cherbourg   yes  False
541         0       3  female   9.00      4      2   31.2750        S   Third  child       False  NaN  Southampton    no  False
542         0       3  female  11.00      4      2   31.2750        S   Third  child       False  NaN  Southampton    no  False
546         1       2  female  19.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
554         1       3  female  22.00      0      0    7.7750        S   Third  woman       False  NaN  Southampton   yes   True
567         0       3  female  29.00      0      4   21.0750        S   Third  woman       False  NaN  Southampton    no  False
580         1       2  female  25.00      1      1   30.0000        S  Second  woman       False  NaN  Southampton   yes  False
585         1       1  female  18.00      0      2   79.6500        S   First  woman       False    E  Southampton   yes  False
600         1       2  female  24.00      2      1   27.0000        S  Second  woman       False  NaN  Southampton   yes  False
608         1       2  female  22.00      1      2   41.5792        C  Second  woman       False  NaN    Cherbourg   yes  False
615         1       2  female  24.00      1      2   65.0000        S  Second  woman       False  NaN  Southampton   yes  False
617         0       3  female  26.00      1      0   16.1000        S   Third  woman       False  NaN  Southampton    no  False
618         1       2  female   4.00      2      1   39.0000        S  Second  child       False    F  Southampton   yes  False
627         1       1  female  21.00      0      0   77.9583        S   First  woman       False    D  Southampton   yes   True
634         0       3  female   9.00      3      2   27.9000        S   Third  child       False  NaN  Southampton    no  False
635         1       2  female  28.00      0      0   13.0000        S  Second  woman       False  NaN  Southampton   yes   True
641         1       1  female  24.00      0      0   69.3000        C   First  woman       False    B    Cherbourg   yes   True
642         0       3  female   2.00      3      2   27.9000        S   Third  child       False  NaN  Southampton    no  False
644         1       3  female   0.75      2      1   19.2583        C   Third  child       False  NaN    Cherbourg   yes  False
649         1       3  female  23.00      0      0    7.5500        S   Third  woman       False  NaN  Southampton   yes   True
651         1       2  female  18.00      0      1   23.0000        S  Second  woman       False  NaN  Southampton   yes  False
654         0       3  female  18.00      0      0    6.7500        Q   Third  woman       False  NaN   Queenstown    no   True
677         1       3  female  18.00      0      0    9.8417        S   Third  woman       False  NaN  Southampton   yes   True
689         1       1  female  15.00      0      1  211.3375        S   First  child       False    B  Southampton   yes  False
691         1       3  female   4.00      0      1   13.4167        C   Third  child       False  NaN    Cherbourg   yes  False
700         1       1  female  18.00      1      0  227.5250        C   First  woman       False    C    Cherbourg   yes  False
702         0       3  female  18.00      0      1   14.4542        C   Third  woman       False  NaN    Cherbourg    no  False
708         1       1  female  22.00      0      0  151.5500        S   First  woman       False  NaN  Southampton   yes   True
710         1       1  female  24.00      0      0   49.5042        C   First  woman       False    C    Cherbourg   yes   True
717         1       2  female  27.00      0      0   10.5000        S  Second  woman       False    E  Southampton   yes   True
720         1       2  female   6.00      0      1   33.0000        S  Second  child       False  NaN  Southampton   yes  False
729         0       3  female  25.00      1      0    7.9250        S   Third  woman       False  NaN  Southampton    no  False
730         1       1  female  29.00      0      0  211.3375        S   First  woman       False    B  Southampton   yes   True
742         1       1  female  21.00      2      2  262.3750        C   First  woman       False    B    Cherbourg   yes  False
750         1       2  female   4.00      1      1   23.0000        S  Second  child       False  NaN  Southampton   yes  False
777         1       3  female   5.00      0      0   12.4750        S   Third  child       False  NaN  Southampton   yes   True
780         1       3  female  13.00      0      0    7.2292        C   Third  child       False  NaN    Cherbourg   yes   True
781         1       1  female  17.00      1      0   57.0000        S   First  woman       False    B  Southampton   yes  False
786         1       3  female  18.00      0      0    7.4958        S   Third  woman       False  NaN  Southampton   yes   True
807         0       3  female  18.00      0      0    7.7750        S   Third  woman       False  NaN  Southampton    no   True
813         0       3  female   6.00      4      2   31.2750        S   Third  child       False  NaN  Southampton    no  False
816         0       3  female  23.00      0      0    7.9250        S   Third  woman       False  NaN  Southampton    no   True
823         1       3  female  27.00      0      1   12.4750        S   Third  woman       False    E  Southampton   yes  False
830         1       3  female  15.00      1      0   14.4542        C   Third  child       False  NaN    Cherbourg   yes  False
852         0       3  female   9.00      1      1   15.2458        C   Third  child       False  NaN    Cherbourg    no  False
853         1       1  female  16.00      0      1   39.4000        S   First  woman       False    D  Southampton   yes  False
855         1       3  female  18.00      0      1    9.3500        S   Third  woman       False  NaN  Southampton   yes  False
858         1       3  female  24.00      0      3   19.2583        C   Third  woman       False  NaN    Cherbourg   yes  False
866         1       2  female  27.00      1      0   13.8583        C  Second  woman       False  NaN    Cherbourg   yes  False
874         1       2  female  28.00      1      0   24.0000        C  Second  woman       False  NaN    Cherbourg   yes  False
875         1       3  female  15.00      0      0    7.2250        C   Third  child       False  NaN    Cherbourg   yes   True
880         1       2  female  25.00      0      1   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
882         0       3  female  22.00      0      0   10.5167        S   Third  woman       False  NaN  Southampton    no   True
887         1       1  female  19.00      0      0   30.0000        S   First  woman       False    B  Southampton   yes   True

Görev 10: Fare'i 500'den büyük veya yaşı 70 den büyük yolcuların bilgilerini gösteriniz.

In [14]:
df[(df["fare"] > 500) | (df["age"] > 70)]

     survived  pclass     sex   age  sibsp  parch      fare embarked  class    who  adult_male deck  embark_town alive  alone
96          0       1    male  71.0      0      0   34.6542        C  First    man        True    A    Cherbourg    no   True
116         0       3    male  70.5      0      0    7.7500        Q  Third    man        True  NaN   Queenstown    no   True
258         1       1  female  35.0      0      0  512.3292        C  First  woman       False  NaN    Cherbourg   yes   True
493         0       1    male  71.0      0      0   49.5042        C  First    man        True  NaN    Cherbourg    no   True
630         1       1    male  80.0      0      0   30.0000        S  First    man        True    A  Southampton   yes   True
679         1       1    male  36.0      0      1  512.3292        C  First    man        True    B    Cherbourg   yes  False
737         1       1    male  35.0      0      0  512.3292        C  First    man        True    B    Cherbourg   yes   True
851         0       3    male  74.0      0      0    7.7750        S  Third    man        True  NaN  Southampton    no   True

Görev 11: Her bir değişkendeki boş değerlerin toplamını bulunuz.

In [15]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Görev 12: who değişkenini dataframe'den düşürün.

In [16]:
df.drop(columns=["who"], inplace=True)

Görev 13: deck değikenindeki boş değerleri deck değişkenin en çok tekrar eden değeri (mode) ile doldurunuz.

In [17]:
deck_mode = df["deck"].mode()[0]
df["deck"].fillna(deck_mode, inplace=True)

/var/folders/rs/862v0z0525z3hzp11q_c2w2c0000gn/T/ipykernel_6026/2818906811.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["deck"].fillna(deck_mode, inplace=True)

0      C
1      C
2      C
3      C
4      C
5      C
6      E
7      C
8      C
9      C
10     G
11     C
12     C
13     C
14     C
15     C
16     C
17     C
18     C
19     C
20     C
21     D
22     C
23     A
24     C
25     C
26     C
27     C
28     C
29     C
30     C
31     B
32     C
33     C
34     C
35     C
36     C
37     C
38     C
39     C
40     C
41     C
42     C
43     C
44     C
45     C
46     C
47     C
48     C
49     C
50     C
51     C
52     D
53     C
54     B
55     C
56     C
57     C
58     C
59     C
60     C
61     B
62     C
63     C
64     C
65     C
66     F
67     C
68     C
69     C
70     C
71     C
72     C
73     C
74     C
75     F
76     C
77     C
78     C
79     C
80     C
81     C
82     C
83     C
84     C
85     C
86     C
87     C
88     C
89     C
90     C
91     C
92     E
93     C
94     C
95     C
96     A
97     D
98     C
99     C
100    C
101    C
102    D
103    C
104    C
105    C
106    C
107    C
108    C
109    C
110    C
111    C
112    C
113    C
114    C
115    C
116    C
117    C
118    B
119    C
120    C
121    C
122    C
123    E
124    D
125    C
126    C
127    C
128    F
129    C
130    C
131    C
132    C
133    C
134    C
135    C
136    D
137    C
138    C
139    B
140    C
141    C
142    C
143    C
144    C
145    C
146    C
147    C
148    F
149    C
150    C
151    C
152    C
153    C
154    C
155    C
156    C
157    C
158    C
159    C
160    C
161    C
162    C
163    C
164    C
165    C
166    E
167    C
168    C
169    C
170    B
171    C
172    C
173    C
174    A
175    C
176    C
177    C
178    C
179    C
180    C
181    C
182    C
183    F
184    C
185    A
186    C
187    C
188    C
189    C
190    C
191    C
192    C
193    F
194    B
195    B
196    C
197    C
198    C
199    C
200    C
201    C
202    C
203    C
204    C
205    G
206    C
207    C
208    C
209    A
210    C
211    C
212    C
213    C
214    C
215    D
216    C
217    C
218    D
219    C
220    C
221    C
222    C
223    C
224    C
225    C
226    C
227    C
228    C
229    C
230    C
231    C
232    C
233    C
234    C
235    C
236    C
237    C
238    C
239    C
240    C
241    C
242    C
243    C
244    C
245    C
246    C
247    C
248    D
249    C
250    C
251    G
252    C
253    C
254    C
255    C
256    C
257    B
258    C
259    C
260    C
261    C
262    E
263    B
264    C
265    C
266    C
267    C
268    C
269    C
270    C
271    C
272    C
273    C
274    C
275    D
276    C
277    C
278    C
279    C
280    C
281    C
282    C
283    C
284    A
285    C
286    C
287    C
288    C
289    C
290    C
291    B
292    D
293    C
294    C
295    C
296    C
297    C
298    C
299    B
300    C
301    C
302    C
303    E
304    C
305    C
306    C
307    C
308    C
309    E
310    C
311    B
312    C
313    C
314    C
315    C
316    C
317    C
318    C
319    E
320    C
321    C
322    C
323    C
324    C
325    C
326    C
327    D
328    C
329    B
330    C
331    C
332    C
333    C
334    C
335    C
336    C
337    E
338    C
339    C
340    F
341    C
342    C
343    C
344    C
345    F
346    C
347    C
348    C
349    C
350    C
351    C
352    C
353    C
354    C
355    C
356    E
357    C
358    C
359    C
360    C
361    C
362    C
363    C
364    C
365    C
366    D
367    C
368    C
369    B
370    E
371    C
372    C
373    C
374    C
375    C
376    C
377    C
378    C
379    C
380    C
381    C
382    C
383    C
384    C
385    C
386    C
387    C
388    C
389    C
390    B
391    C
392    C
393    D
394    G
395    C
396    C
397    C
398    C
399    C
400    C
401    C
402    C
403    C
404    C
405    C
406    C
407    C
408    C
409    C
410    C
411    C
412    C
413    C
414    C
415    C
416    C
417    C
418    C
419    C
420    C
421    C
422    C
423    C
424    C
425    C
426    C
427    C
428    C
429    E
430    C
431    C
432    C
433    C
434    E
435    B
436    C
437    C
438    C
439    C
440    C
441    C
442    C
443    C
444    C
445    A
446    C
447    C
448    C
449    C
450    C
451    C
452    C
453    C
454    C
455    C
456    E
457    D
458    C
459    C
460    E
461    C
462    E
463    C
464    C
465    C
466    C
467    C
468    C
469    C
470    C
471    C
472    C
473    D
474    C
475    A
476    C
477    C
478    C
479    C
480    C
481    C
482    C
483    C
484    B
485    C
486    C
487    B
488    C
489    C
490    C
491    C
492    C
493    C
494    C
495    C
496    D
497    C
498    C
499    C
500    C
501    C
502    C
503    C
504    B
505    C
506    C
507    C
508    C
509    C
510    C
511    C
512    E
513    C
514    C
515    D
516    F
517    C
518    C
519    C
520    B
521    C
522    C
523    B
524    C
525    C
526    C
527    C
528    C
529    C
530    C
531    C
532    C
533    C
534    C
535    C
536    B
537    C
538    C
539    B
540    B
541    C
542    C
543    C
544    C
545    C
546    C
547    C
548    C
549    C
550    C
551    C
552    C
553    C
554    C
555    C
556    A
557    C
558    E
559    C
560    C
561    C
562    C
563    C
564    C
565    C
566    C
567    C
568    C
569    C
570    C
571    C
572    E
573    C
574    C
575    C
576    C
577    E
578    C
579    C
580    C
581    C
582    C
583    A
584    C
585    E
586    C
587    B
588    C
589    C
590    C
591    D
592    C
593    C
594    C
595    C
596    C
597    C
598    C
599    A
600    C
601    C
602    C
603    C
604    C
605    C
606    C
607    C
608    C
609    C
610    C
611    C
612    C
613    C
614    C
615    C
616    C
617    C
618    F
619    C
620    C
621    D
622    C
623    C
624    C
625    D
626    C
627    D
628    C
629    C
630    A
631    C
632    B
633    C
634    C
635    C
636    C
637    C
638    C
639    C
640    C
641    B
642    C
643    C
644    C
645    D
646    C
647    A
648    C
649    C
650    C
651    C
652    C
653    C
654    C
655    C
656    C
657    C
658    C
659    D
660    C
661    C
662    E
663    C
664    C
665    C
666    C
667    C
668    C
669    C
670    C
671    B
672    C
673    C
674    C
675    C
676    C
677    C
678    C
679    B
680    C
681    D
682    C
683    C
684    C
685    C
686    C
687    C
688    C
689    B
690    B
691    C
692    C
693    C
694    C
695    C
696    C
697    C
698    C
699    F
700    C
701    E
702    C
703    C
704    C
705    C
706    C
707    E
708    C
709    C
710    C
711    C
712    C
713    C
714    C
715    F
716    C
717    E
718    C
719    C
720    C
721    C
722    C
723    C
724    E
725    C
726    C
727    C
728    C
729    C
730    B
731    C
732    C
733    C
734    C
735    C
736    C
737    B
738    C
739    C
740    D
741    C
742    B
743    C
744    C
745    B
746    C
747    C
748    D
749    C
750    C
751    E
752    C
753    C
754    C
755    C
756    C
757    C
758    C
759    B
760    C
761    C
762    C
763    B
764    C
765    D
766    C
767    C
768    C
769    C
770    C
771    C
772    E
773    C
774    C
775    C
776    F
777    C
778    C
779    B
780    C
781    B
782    D
783    C
784    C
785    C
786    C
787    C
788    C
789    B
790    C
791    C
792    C
793    C
794    C
795    C
796    D
797    C
798    C
799    C
800    C
801    C
802    B
803    C
804    C
805    C
806    A
807    C
808    C
809    E
810    C
811    C
812    C
813    C
814    C
815    B
816    C
817    C
818    C
819    C
820    B
821    C
822    C
823    E
824    C
825    C
826    C
827    C
828    C
829    B
830    C
831    C
832    C
833    C
834    C
835    E
836    C
837    C
838    C
839    C
840    C
841    C
842    C
843    C
844    C
845    C
846    C
847    C
848    C
849    C
850    C
851    C
852    C
853    D
854    C
855    C
856    C
857    E
858    C
859    C
860    C
861    C
862    D
863    C
864    C
865    C
866    C
867    A
868    C
869    C
870    C
871    D
872    B
873    C
874    C
875    C
876    C
877    C
878    C
879    C
880    C
881    C
882    C
883    C
884    C
885    C
886    C
887    B
888    C
889    C
890    C
Name: deck, dtype: category
Categories (7, str): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

Görev 14: age değikenindeki boş değerleri age değişkenin medyanı ile doldurun.

In [18]:
df["age"].fillna(df["age"].median(), inplace=True)

/var/folders/rs/862v0z0525z3hzp11q_c2w2c0000gn/T/ipykernel_6026/3040546416.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["age"].fillna(df["age"].median(), inplace=True)

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
5      28.00
6      54.00
7       2.00
8      27.00
9      14.00
10      4.00
11     58.00
12     20.00
13     39.00
14     14.00
15     55.00
16      2.00
17     28.00
18     31.00
19     28.00
20     35.00
21     34.00
22     15.00
23     28.00
24      8.00
25     38.00
26     28.00
27     19.00
28     28.00
29     28.00
30     40.00
31     28.00
32     28.00
33     66.00
34     28.00
35     42.00
36     28.00
37     21.00
38     18.00
39     14.00
40     40.00
41     27.00
42     28.00
43      3.00
44     19.00
45     28.00
46     28.00
47     28.00
48     28.00
49     18.00
50      7.00
51     21.00
52     49.00
53     29.00
54     65.00
55     28.00
56     21.00
57     28.50
58      5.00
59     11.00
60     22.00
61     38.00
62     45.00
63      4.00
64     28.00
65     28.00
66     29.00
67     19.00
68     17.00
69     26.00
70     32.00
71     16.00
72     21.00
73     26.00
74     32.00
75     25.00
76     28.00
77     28.00
78      0.83
79     30.00
80     22.00
81     29.00
82     28.00
83     28.00
84     17.00
85     33.00
86     16.00
87     28.00
88     23.00
89     24.00
90     29.00
91     20.00
92     46.00
93     26.00
94     59.00
95     28.00
96     71.00
97     23.00
98     34.00
99     34.00
100    28.00
101    28.00
102    21.00
103    33.00
104    37.00
105    28.00
106    21.00
107    28.00
108    38.00
109    28.00
110    47.00
111    14.50
112    22.00
113    20.00
114    17.00
115    21.00
116    70.50
117    29.00
118    24.00
119     2.00
120    21.00
121    28.00
122    32.50
123    32.50
124    54.00
125    12.00
126    28.00
127    24.00
128    28.00
129    45.00
130    33.00
131    20.00
132    47.00
133    29.00
134    25.00
135    23.00
136    19.00
137    37.00
138    16.00
139    24.00
140    28.00
141    22.00
142    24.00
143    19.00
144    18.00
145    19.00
146    27.00
147     9.00
148    36.50
149    42.00
150    51.00
151    22.00
152    55.50
153    40.50
154    28.00
155    51.00
156    16.00
157    30.00
158    28.00
159    28.00
160    44.00
161    40.00
162    26.00
163    17.00
164     1.00
165     9.00
166    28.00
167    45.00
168    28.00
169    28.00
170    61.00
171     4.00
172     1.00
173    21.00
174    56.00
175    18.00
176    28.00
177    50.00
178    30.00
179    36.00
180    28.00
181    28.00
182     9.00
183     1.00
184     4.00
185    28.00
186    28.00
187    45.00
188    40.00
189    36.00
190    32.00
191    19.00
192    19.00
193     3.00
194    44.00
195    58.00
196    28.00
197    42.00
198    28.00
199    24.00
200    28.00
201    28.00
202    34.00
203    45.50
204    18.00
205     2.00
206    32.00
207    26.00
208    16.00
209    40.00
210    24.00
211    35.00
212    22.00
213    30.00
214    28.00
215    31.00
216    27.00
217    42.00
218    32.00
219    30.00
220    16.00
221    27.00
222    51.00
223    28.00
224    38.00
225    22.00
226    19.00
227    20.50
228    18.00
229    28.00
230    35.00
231    29.00
232    59.00
233     5.00
234    24.00
235    28.00
236    44.00
237     8.00
238    19.00
239    33.00
240    28.00
241    28.00
242    29.00
243    22.00
244    30.00
245    44.00
246    25.00
247    24.00
248    37.00
249    54.00
250    28.00
251    29.00
252    62.00
253    30.00
254    41.00
255    29.00
256    28.00
257    30.00
258    35.00
259    50.00
260    28.00
261     3.00
262    52.00
263    40.00
264    28.00
265    36.00
266    16.00
267    25.00
268    58.00
269    35.00
270    28.00
271    25.00
272    41.00
273    37.00
274    28.00
275    63.00
276    45.00
277    28.00
278     7.00
279    35.00
280    65.00
281    28.00
282    16.00
283    19.00
284    28.00
285    33.00
286    30.00
287    22.00
288    42.00
289    22.00
290    26.00
291    19.00
292    36.00
293    24.00
294    24.00
295    28.00
296    23.50
297     2.00
298    28.00
299    50.00
300    28.00
301    28.00
302    19.00
303    28.00
304    28.00
305     0.92
306    28.00
307    17.00
308    30.00
309    30.00
310    24.00
311    18.00
312    26.00
313    28.00
314    43.00
315    26.00
316    24.00
317    54.00
318    31.00
319    40.00
320    22.00
321    27.00
322    30.00
323    22.00
324    28.00
325    36.00
326    61.00
327    36.00
328    31.00
329    16.00
330    28.00
331    45.50
332    38.00
333    16.00
334    28.00
335    28.00
336    29.00
337    41.00
338    45.00
339    45.00
340     2.00
341    24.00
342    28.00
343    25.00
344    36.00
345    24.00
346    40.00
347    28.00
348     3.00
349    42.00
350    23.00
351    28.00
352    15.00
353    25.00
354    28.00
355    28.00
356    22.00
357    38.00
358    28.00
359    28.00
360    40.00
361    29.00
362    45.00
363    35.00
364    28.00
365    30.00
366    60.00
367    28.00
368    28.00
369    24.00
370    25.00
371    18.00
372    19.00
373    22.00
374     3.00
375    28.00
376    22.00
377    27.00
378    20.00
379    19.00
380    42.00
381     1.00
382    32.00
383    35.00
384    28.00
385    18.00
386     1.00
387    36.00
388    28.00
389    17.00
390    36.00
391    21.00
392    28.00
393    23.00
394    24.00
395    22.00
396    31.00
397    46.00
398    23.00
399    28.00
400    39.00
401    26.00
402    21.00
403    28.00
404    20.00
405    34.00
406    51.00
407     3.00
408    21.00
409    28.00
410    28.00
411    28.00
412    33.00
413    28.00
414    44.00
415    28.00
416    34.00
417    18.00
418    30.00
419    10.00
420    28.00
421    21.00
422    29.00
423    28.00
424    18.00
425    28.00
426    28.00
427    19.00
428    28.00
429    32.00
430    28.00
431    28.00
432    42.00
433    17.00
434    50.00
435    14.00
436    21.00
437    24.00
438    64.00
439    31.00
440    45.00
441    20.00
442    25.00
443    28.00
444    28.00
445     4.00
446    13.00
447    34.00
448     5.00
449    52.00
450    36.00
451    28.00
452    30.00
453    49.00
454    28.00
455    29.00
456    65.00
457    28.00
458    50.00
459    28.00
460    48.00
461    34.00
462    47.00
463    48.00
464    28.00
465    38.00
466    28.00
467    56.00
468    28.00
469     0.75
470    28.00
471    38.00
472    33.00
473    23.00
474    22.00
475    28.00
476    34.00
477    29.00
478    22.00
479     2.00
480     9.00
481    28.00
482    50.00
483    63.00
484    25.00
485    28.00
486    35.00
487    58.00
488    30.00
489     9.00
490    28.00
491    21.00
492    55.00
493    71.00
494    21.00
495    28.00
496    54.00
497    28.00
498    25.00
499    24.00
500    17.00
501    21.00
502    28.00
503    37.00
504    16.00
505    18.00
506    33.00
507    28.00
508    28.00
509    26.00
510    29.00
511    28.00
512    36.00
513    54.00
514    24.00
515    47.00
516    34.00
517    28.00
518    36.00
519    32.00
520    30.00
521    22.00
522    28.00
523    44.00
524    28.00
525    40.50
526    50.00
527    28.00
528    39.00
529    23.00
530     2.00
531    28.00
532    17.00
533    28.00
534    30.00
535     7.00
536    45.00
537    30.00
538    28.00
539    22.00
540    36.00
541     9.00
542    11.00
543    32.00
544    50.00
545    64.00
546    19.00
547    28.00
548    33.00
549     8.00
550    17.00
551    27.00
552    28.00
553    22.00
554    22.00
555    62.00
556    48.00
557    28.00
558    39.00
559    36.00
560    28.00
561    40.00
562    28.00
563    28.00
564    28.00
565    24.00
566    19.00
567    29.00
568    28.00
569    32.00
570    62.00
571    53.00
572    36.00
573    28.00
574    16.00
575    19.00
576    34.00
577    39.00
578    28.00
579    32.00
580    25.00
581    39.00
582    54.00
583    36.00
584    28.00
585    18.00
586    47.00
587    60.00
588    22.00
589    28.00
590    35.00
591    52.00
592    47.00
593    28.00
594    37.00
595    36.00
596    28.00
597    49.00
598    28.00
599    49.00
600    24.00
601    28.00
602    28.00
603    44.00
604    35.00
605    36.00
606    30.00
607    27.00
608    22.00
609    40.00
610    39.00
611    28.00
612    28.00
613    28.00
614    35.00
615    24.00
616    34.00
617    26.00
618     4.00
619    26.00
620    27.00
621    42.00
622    20.00
623    21.00
624    21.00
625    61.00
626    57.00
627    21.00
628    26.00
629    28.00
630    80.00
631    51.00
632    32.00
633    28.00
634     9.00
635    28.00
636    32.00
637    31.00
638    41.00
639    28.00
640    20.00
641    24.00
642     2.00
643    28.00
644     0.75
645    48.00
646    19.00
647    56.00
648    28.00
649    23.00
650    28.00
651    18.00
652    21.00
653    28.00
654    18.00
655    24.00
656    28.00
657    32.00
658    23.00
659    58.00
660    50.00
661    40.00
662    47.00
663    36.00
664    20.00
665    32.00
666    25.00
667    28.00
668    43.00
669    28.00
670    40.00
671    31.00
672    70.00
673    31.00
674    28.00
675    18.00
676    24.50
677    18.00
678    43.00
679    36.00
680    28.00
681    27.00
682    20.00
683    14.00
684    60.00
685    25.00
686    14.00
687    19.00
688    18.00
689    15.00
690    31.00
691     4.00
692    28.00
693    25.00
694    60.00
695    52.00
696    44.00
697    28.00
698    49.00
699    42.00
700    18.00
701    35.00
702    18.00
703    25.00
704    26.00
705    39.00
706    45.00
707    42.00
708    22.00
709    28.00
710    24.00
711    28.00
712    48.00
713    29.00
714    52.00
715    19.00
716    38.00
717    27.00
718    28.00
719    33.00
720     6.00
721    17.00
722    34.00
723    50.00
724    27.00
725    20.00
726    30.00
727    28.00
728    25.00
729    25.00
730    29.00
731    11.00
732    28.00
733    23.00
734    23.00
735    28.50
736    48.00
737    35.00
738    28.00
739    28.00
740    28.00
741    36.00
742    21.00
743    24.00
744    31.00
745    70.00
746    16.00
747    30.00
748    19.00
749    31.00
750     4.00
751     6.00
752    33.00
753    23.00
754    48.00
755     0.67
756    28.00
757    18.00
758    34.00
759    33.00
760    28.00
761    41.00
762    20.00
763    36.00
764    16.00
765    51.00
766    28.00
767    30.50
768    28.00
769    32.00
770    24.00
771    48.00
772    57.00
773    28.00
774    54.00
775    18.00
776    28.00
777     5.00
778    28.00
779    43.00
780    13.00
781    17.00
782    29.00
783    28.00
784    25.00
785    25.00
786    18.00
787     8.00
788     1.00
789    46.00
790    28.00
791    16.00
792    28.00
793    28.00
794    25.00
795    39.00
796    49.00
797    31.00
798    30.00
799    30.00
800    34.00
801    31.00
802    11.00
803     0.42
804    27.00
805    31.00
806    39.00
807    18.00
808    39.00
809    33.00
810    26.00
811    39.00
812    35.00
813     6.00
814    30.50
815    28.00
816    23.00
817    31.00
818    43.00
819    10.00
820    52.00
821    27.00
822    38.00
823    27.00
824     2.00
825    28.00
826    28.00
827     1.00
828    28.00
829    62.00
830    15.00
831     0.83
832    28.00
833    23.00
834    18.00
835    39.00
836    21.00
837    28.00
838    32.00
839    28.00
840    20.00
841    16.00
842    30.00
843    34.50
844    17.00
845    42.00
846    28.00
847    35.00
848    28.00
849    28.00
850     4.00
851    74.00
852     9.00
853    16.00
854    44.00
855    18.00
856    45.00
857    51.00
858    24.00
859    28.00
860    41.00
861    21.00
862    48.00
863    28.00
864    24.00
865    42.00
866    27.00
867    31.00
868    28.00
869     4.00
870    26.00
871    47.00
872    33.00
873    47.00
874    28.00
875    15.00
876    20.00
877    19.00
878    28.00
879    56.00
880    25.00
881    33.00
882    22.00
883    28.00
884    25.00
885    39.00
886    27.00
887    19.00
888    28.00
889    26.00
890    32.00
Name: age, dtype: float64

Görev 15: survived değişkeninin Pclass ve Cinsiyet değişkenleri kırılımınında sum, count, mean değerlerini bulunuz.

In [20]:
df.groupby(["pclass", "sex"]).agg({"survived": ["sum", "count", "mean"]})

              survived
                   sum count      mean
pclass sex
1      female       91    94  0.968085
       male         45   122  0.368852
2      female       70    76  0.921053
       male         17   108  0.157407
3      female       72   144  0.500000
       male         47   347  0.135447

Görev 16: 30 yaşın altında olanlar 1, 30'a eşit ve üstünde olanlara 0 vericek bir fonksiyon yazınız.
Yazdığınız fonksiyonu kullanarak titanik veri setinde age_flag adında bir değişken oluşturunuz oluşturunuz. (apply ve lambda yapılarını kullanınız)

In [21]:
def age_flag_func(age):
    return 1 if age < 30 else 0

df["age_flag"] = df["age"].apply(lambda x: age_flag_func(x))

Görev 17: Seaborn kütüphanesi içerisinden Tips veri setini tanımlayınız.

In [22]:
df = sns.load_dataset("tips")

Görev 18: Time değişkeninin kategorilerine (Dinner, Lunch) göre total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.

In [23]:
df.groupby("time")["total_bill"].agg(["sum", "min", "max", "mean"])

            sum   min    max       mean
time
Lunch   1167.47  7.51  43.11  17.168676
Dinner  3660.30  3.07  50.81  20.797159

Görev 19: Günlere ve time göre total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.

In [24]:
df.groupby(["day", "time"])["total_bill"].agg(["sum", "min", "max", "mean"])

                 sum    min    max       mean
day  time
Thur Lunch   1077.55   7.51  43.11  17.664754
     Dinner    18.78  18.78  18.78  18.780000
Fri  Lunch     89.92   8.58  16.27  12.845714
     Dinner   235.96   5.75  40.17  19.663333
Sat  Dinner  1778.40   3.07  50.81  20.441379
Sun  Dinner  1627.16   7.25  48.17  21.410000

Görev 20: Lunch zamanına ve kadın müşterilere ait total_bill ve tip değerlerinin day'e göre toplamını, min, max ve ortalamasını bulunuz.

In [26]:
df[(df["time"] == "Lunch") & (df["sex"] == "Female")].groupby("day")[["total_bill", "tip"]].agg(["sum", "min", "max", "mean"])

     total_bill                            tip
            sum    min    max      mean    sum   min   max      mean
day
Thur     516.11   8.35  43.11  16.64871  79.42  1.25  5.17  2.561935
Fri       55.76  10.09  16.27  13.94000  10.98  2.00  3.48  2.745000

Görev 21: size'i 3'ten küçük, total_bill'i 10'dan büyük olan siparişlerin ortalaması nedir?

In [29]:
df[(df["size"] < 3) & (df["total_bill"] > 10)].select_dtypes(include="number").mean()

total_bill    17.184965
tip            2.638811
size           1.993007
dtype: float64

Görev 22: total_bill_tip_sum adında yeni bir değişken oluşturun. Her bir müşterinin ödediği totalbill ve tip in toplamını versin.

In [30]:
total_bill_tip_sum = df["total_bill"] + df["tip"]
df["total_bill_tip_sum"] = total_bill_tip_sum
df

     total_bill    tip     sex smoker   day    time  size  total_bill_tip_sum
0         16.99   1.01  Female     No   Sun  Dinner     2               18.00
1         10.34   1.66    Male     No   Sun  Dinner     3               12.00
2         21.01   3.50    Male     No   Sun  Dinner     3               24.51
3         23.68   3.31    Male     No   Sun  Dinner     2               26.99
4         24.59   3.61  Female     No   Sun  Dinner     4               28.20
5         25.29   4.71    Male     No   Sun  Dinner     4               30.00
6          8.77   2.00    Male     No   Sun  Dinner     2               10.77
7         26.88   3.12    Male     No   Sun  Dinner     4               30.00
8         15.04   1.96    Male     No   Sun  Dinner     2               17.00
9         14.78   3.23    Male     No   Sun  Dinner     2               18.01
10        10.27   1.71    Male     No   Sun  Dinner     2               11.98
11        35.26   5.00  Female     No   Sun  Dinner     4               40.26
12        15.42   1.57    Male     No   Sun  Dinner     2               16.99
13        18.43   3.00    Male     No   Sun  Dinner     4               21.43
14        14.83   3.02  Female     No   Sun  Dinner     2               17.85
15        21.58   3.92    Male     No   Sun  Dinner     2               25.50
16        10.33   1.67  Female     No   Sun  Dinner     3               12.00
17        16.29   3.71    Male     No   Sun  Dinner     3               20.00
18        16.97   3.50  Female     No   Sun  Dinner     3               20.47
19        20.65   3.35    Male     No   Sat  Dinner     3               24.00
20        17.92   4.08    Male     No   Sat  Dinner     2               22.00
21        20.29   2.75  Female     No   Sat  Dinner     2               23.04
22        15.77   2.23  Female     No   Sat  Dinner     2               18.00
23        39.42   7.58    Male     No   Sat  Dinner     4               47.00
24        19.82   3.18    Male     No   Sat  Dinner     2               23.00
25        17.81   2.34    Male     No   Sat  Dinner     4               20.15
26        13.37   2.00    Male     No   Sat  Dinner     2               15.37
27        12.69   2.00    Male     No   Sat  Dinner     2               14.69
28        21.70   4.30    Male     No   Sat  Dinner     2               26.00
29        19.65   3.00  Female     No   Sat  Dinner     2               22.65
30         9.55   1.45    Male     No   Sat  Dinner     2               11.00
31        18.35   2.50    Male     No   Sat  Dinner     4               20.85
32        15.06   3.00  Female     No   Sat  Dinner     2               18.06
33        20.69   2.45  Female     No   Sat  Dinner     4               23.14
34        17.78   3.27    Male     No   Sat  Dinner     2               21.05
35        24.06   3.60    Male     No   Sat  Dinner     3               27.66
36        16.31   2.00    Male     No   Sat  Dinner     3               18.31
37        16.93   3.07  Female     No   Sat  Dinner     3               20.00
38        18.69   2.31    Male     No   Sat  Dinner     3               21.00
39        31.27   5.00    Male     No   Sat  Dinner     3               36.27
40        16.04   2.24    Male     No   Sat  Dinner     3               18.28
41        17.46   2.54    Male     No   Sun  Dinner     2               20.00
42        13.94   3.06    Male     No   Sun  Dinner     2               17.00
43         9.68   1.32    Male     No   Sun  Dinner     2               11.00
44        30.40   5.60    Male     No   Sun  Dinner     4               36.00
45        18.29   3.00    Male     No   Sun  Dinner     2               21.29
46        22.23   5.00    Male     No   Sun  Dinner     2               27.23
47        32.40   6.00    Male     No   Sun  Dinner     4               38.40
48        28.55   2.05    Male     No   Sun  Dinner     3               30.60
49        18.04   3.00    Male     No   Sun  Dinner     2               21.04
50        12.54   2.50    Male     No   Sun  Dinner     2               15.04
51        10.29   2.60  Female     No   Sun  Dinner     2               12.89
52        34.81   5.20  Female     No   Sun  Dinner     4               40.01
53         9.94   1.56    Male     No   Sun  Dinner     2               11.50
54        25.56   4.34    Male     No   Sun  Dinner     4               29.90
55        19.49   3.51    Male     No   Sun  Dinner     2               23.00
56        38.01   3.00    Male    Yes   Sat  Dinner     4               41.01
57        26.41   1.50  Female     No   Sat  Dinner     2               27.91
58        11.24   1.76    Male    Yes   Sat  Dinner     2               13.00
59        48.27   6.73    Male     No   Sat  Dinner     4               55.00
60        20.29   3.21    Male    Yes   Sat  Dinner     2               23.50
61        13.81   2.00    Male    Yes   Sat  Dinner     2               15.81
62        11.02   1.98    Male    Yes   Sat  Dinner     2               13.00
63        18.29   3.76    Male    Yes   Sat  Dinner     4               22.05
64        17.59   2.64    Male     No   Sat  Dinner     3               20.23
65        20.08   3.15    Male     No   Sat  Dinner     3               23.23
66        16.45   2.47  Female     No   Sat  Dinner     2               18.92
67         3.07   1.00  Female    Yes   Sat  Dinner     1                4.07
68        20.23   2.01    Male     No   Sat  Dinner     2               22.24
69        15.01   2.09    Male    Yes   Sat  Dinner     2               17.10
70        12.02   1.97    Male     No   Sat  Dinner     2               13.99
71        17.07   3.00  Female     No   Sat  Dinner     3               20.07
72        26.86   3.14  Female    Yes   Sat  Dinner     2               30.00
73        25.28   5.00  Female    Yes   Sat  Dinner     2               30.28
74        14.73   2.20  Female     No   Sat  Dinner     2               16.93
75        10.51   1.25    Male     No   Sat  Dinner     2               11.76
76        17.92   3.08    Male    Yes   Sat  Dinner     2               21.00
77        27.20   4.00    Male     No  Thur   Lunch     4               31.20
78        22.76   3.00    Male     No  Thur   Lunch     2               25.76
79        17.29   2.71    Male     No  Thur   Lunch     2               20.00
80        19.44   3.00    Male    Yes  Thur   Lunch     2               22.44
81        16.66   3.40    Male     No  Thur   Lunch     2               20.06
82        10.07   1.83  Female     No  Thur   Lunch     1               11.90
83        32.68   5.00    Male    Yes  Thur   Lunch     2               37.68
84        15.98   2.03    Male     No  Thur   Lunch     2               18.01
85        34.83   5.17  Female     No  Thur   Lunch     4               40.00
86        13.03   2.00    Male     No  Thur   Lunch     2               15.03
87        18.28   4.00    Male     No  Thur   Lunch     2               22.28
88        24.71   5.85    Male     No  Thur   Lunch     2               30.56
89        21.16   3.00    Male     No  Thur   Lunch     2               24.16
90        28.97   3.00    Male    Yes   Fri  Dinner     2               31.97
91        22.49   3.50    Male     No   Fri  Dinner     2               25.99
92         5.75   1.00  Female    Yes   Fri  Dinner     2                6.75
93        16.32   4.30  Female    Yes   Fri  Dinner     2               20.62
94        22.75   3.25  Female     No   Fri  Dinner     2               26.00
95        40.17   4.73    Male    Yes   Fri  Dinner     4               44.90
96        27.28   4.00    Male    Yes   Fri  Dinner     2               31.28
97        12.03   1.50    Male    Yes   Fri  Dinner     2               13.53
98        21.01   3.00    Male    Yes   Fri  Dinner     2               24.01
99        12.46   1.50    Male     No   Fri  Dinner     2               13.96
100       11.35   2.50  Female    Yes   Fri  Dinner     2               13.85
101       15.38   3.00  Female    Yes   Fri  Dinner     2               18.38
102       44.30   2.50  Female    Yes   Sat  Dinner     3               46.80
103       22.42   3.48  Female    Yes   Sat  Dinner     2               25.90
104       20.92   4.08  Female     No   Sat  Dinner     2               25.00
105       15.36   1.64    Male    Yes   Sat  Dinner     2               17.00
106       20.49   4.06    Male    Yes   Sat  Dinner     2               24.55
107       25.21   4.29    Male    Yes   Sat  Dinner     2               29.50
108       18.24   3.76    Male     No   Sat  Dinner     2               22.00
109       14.31   4.00  Female    Yes   Sat  Dinner     2               18.31
110       14.00   3.00    Male     No   Sat  Dinner     2               17.00
111        7.25   1.00  Female     No   Sat  Dinner     1                8.25
112       38.07   4.00    Male     No   Sun  Dinner     3               42.07
113       23.95   2.55    Male     No   Sun  Dinner     2               26.50
114       25.71   4.00  Female     No   Sun  Dinner     3               29.71
115       17.31   3.50  Female     No   Sun  Dinner     2               20.81
116       29.93   5.07    Male     No   Sun  Dinner     4               35.00
117       10.65   1.50  Female     No  Thur   Lunch     2               12.15
118       12.43   1.80  Female     No  Thur   Lunch     2               14.23
119       24.08   2.92  Female     No  Thur   Lunch     4               27.00
120       11.69   2.31    Male     No  Thur   Lunch     2               14.00
121       13.42   1.68  Female     No  Thur   Lunch     2               15.10
122       14.26   2.50    Male     No  Thur   Lunch     2               16.76
123       15.95   2.00    Male     No  Thur   Lunch     2               17.95
124       12.48   2.52  Female     No  Thur   Lunch     2               15.00
125       29.80   4.20  Female     No  Thur   Lunch     6               34.00
126        8.52   1.48    Male     No  Thur   Lunch     2               10.00
127       14.52   2.00  Female     No  Thur   Lunch     2               16.52
128       11.38   2.00  Female     No  Thur   Lunch     2               13.38
129       22.82   2.18    Male     No  Thur   Lunch     3               25.00
130       19.08   1.50    Male     No  Thur   Lunch     2               20.58
131       20.27   2.83  Female     No  Thur   Lunch     2               23.10
132       11.17   1.50  Female     No  Thur   Lunch     2               12.67
133       12.26   2.00  Female     No  Thur   Lunch     2               14.26
134       18.26   3.25  Female     No  Thur   Lunch     2               21.51
135        8.51   1.25  Female     No  Thur   Lunch     2                9.76
136       10.33   2.00  Female     No  Thur   Lunch     2               12.33
137       14.15   2.00  Female     No  Thur   Lunch     2               16.15
138       16.00   2.00    Male    Yes  Thur   Lunch     2               18.00
139       13.16   2.75  Female     No  Thur   Lunch     2               15.91
140       17.47   3.50  Female     No  Thur   Lunch     2               20.97
141       34.30   6.70    Male     No  Thur   Lunch     6               41.00
142       41.19   5.00    Male     No  Thur   Lunch     5               46.19
143       27.05   5.00  Female     No  Thur   Lunch     6               32.05
144       16.43   2.30  Female     No  Thur   Lunch     2               18.73
145        8.35   1.50  Female     No  Thur   Lunch     2                9.85
146       18.64   1.36  Female     No  Thur   Lunch     3               20.00
147       11.87   1.63  Female     No  Thur   Lunch     2               13.50
148        9.78   1.73    Male     No  Thur   Lunch     2               11.51
149        7.51   2.00    Male     No  Thur   Lunch     2                9.51
150       14.07   2.50    Male     No   Sun  Dinner     2               16.57
151       13.13   2.00    Male     No   Sun  Dinner     2               15.13
152       17.26   2.74    Male     No   Sun  Dinner     3               20.00
153       24.55   2.00    Male     No   Sun  Dinner     4               26.55
154       19.77   2.00    Male     No   Sun  Dinner     4               21.77
155       29.85   5.14  Female     No   Sun  Dinner     5               34.99
156       48.17   5.00    Male     No   Sun  Dinner     6               53.17
157       25.00   3.75  Female     No   Sun  Dinner     4               28.75
158       13.39   2.61  Female     No   Sun  Dinner     2               16.00
159       16.49   2.00    Male     No   Sun  Dinner     4               18.49
160       21.50   3.50    Male     No   Sun  Dinner     4               25.00
161       12.66   2.50    Male     No   Sun  Dinner     2               15.16
162       16.21   2.00  Female     No   Sun  Dinner     3               18.21
163       13.81   2.00    Male     No   Sun  Dinner     2               15.81
164       17.51   3.00  Female    Yes   Sun  Dinner     2               20.51
165       24.52   3.48    Male     No   Sun  Dinner     3               28.00
166       20.76   2.24    Male     No   Sun  Dinner     2               23.00
167       31.71   4.50    Male     No   Sun  Dinner     4               36.21
168       10.59   1.61  Female    Yes   Sat  Dinner     2               12.20
169       10.63   2.00  Female    Yes   Sat  Dinner     2               12.63
170       50.81  10.00    Male    Yes   Sat  Dinner     3               60.81
171       15.81   3.16    Male    Yes   Sat  Dinner     2               18.97
172        7.25   5.15    Male    Yes   Sun  Dinner     2               12.40
173       31.85   3.18    Male    Yes   Sun  Dinner     2               35.03
174       16.82   4.00    Male    Yes   Sun  Dinner     2               20.82
175       32.90   3.11    Male    Yes   Sun  Dinner     2               36.01
176       17.89   2.00    Male    Yes   Sun  Dinner     2               19.89
177       14.48   2.00    Male    Yes   Sun  Dinner     2               16.48
178        9.60   4.00  Female    Yes   Sun  Dinner     2               13.60
179       34.63   3.55    Male    Yes   Sun  Dinner     2               38.18
180       34.65   3.68    Male    Yes   Sun  Dinner     4               38.33
181       23.33   5.65    Male    Yes   Sun  Dinner     2               28.98
182       45.35   3.50    Male    Yes   Sun  Dinner     3               48.85
183       23.17   6.50    Male    Yes   Sun  Dinner     4               29.67
184       40.55   3.00    Male    Yes   Sun  Dinner     2               43.55
185       20.69   5.00    Male     No   Sun  Dinner     5               25.69
186       20.90   3.50  Female    Yes   Sun  Dinner     3               24.40
187       30.46   2.00    Male    Yes   Sun  Dinner     5               32.46
188       18.15   3.50  Female    Yes   Sun  Dinner     3               21.65
189       23.10   4.00    Male    Yes   Sun  Dinner     3               27.10
190       15.69   1.50    Male    Yes   Sun  Dinner     2               17.19
191       19.81   4.19  Female    Yes  Thur   Lunch     2               24.00
192       28.44   2.56    Male    Yes  Thur   Lunch     2               31.00
193       15.48   2.02    Male    Yes  Thur   Lunch     2               17.50
194       16.58   4.00    Male    Yes  Thur   Lunch     2               20.58
195        7.56   1.44    Male     No  Thur   Lunch     2                9.00
196       10.34   2.00    Male    Yes  Thur   Lunch     2               12.34
197       43.11   5.00  Female    Yes  Thur   Lunch     4               48.11
198       13.00   2.00  Female    Yes  Thur   Lunch     2               15.00
199       13.51   2.00    Male    Yes  Thur   Lunch     2               15.51
200       18.71   4.00    Male    Yes  Thur   Lunch     3               22.71
201       12.74   2.01  Female    Yes  Thur   Lunch     2               14.75
202       13.00   2.00  Female    Yes  Thur   Lunch     2               15.00
203       16.40   2.50  Female    Yes  Thur   Lunch     2               18.90
204       20.53   4.00    Male    Yes  Thur   Lunch     4               24.53
205       16.47   3.23  Female    Yes  Thur   Lunch     3               19.70
206       26.59   3.41    Male    Yes   Sat  Dinner     3               30.00
207       38.73   3.00    Male    Yes   Sat  Dinner     4               41.73
208       24.27   2.03    Male    Yes   Sat  Dinner     2               26.30
209       12.76   2.23  Female    Yes   Sat  Dinner     2               14.99
210       30.06   2.00    Male    Yes   Sat  Dinner     3               32.06
211       25.89   5.16    Male    Yes   Sat  Dinner     4               31.05
212       48.33   9.00    Male     No   Sat  Dinner     4               57.33
213       13.27   2.50  Female    Yes   Sat  Dinner     2               15.77
214       28.17   6.50  Female    Yes   Sat  Dinner     3               34.67
215       12.90   1.10  Female    Yes   Sat  Dinner     2               14.00
216       28.15   3.00    Male    Yes   Sat  Dinner     5               31.15
217       11.59   1.50    Male    Yes   Sat  Dinner     2               13.09
218        7.74   1.44    Male    Yes   Sat  Dinner     2                9.18
219       30.14   3.09  Female    Yes   Sat  Dinner     4               33.23
220       12.16   2.20    Male    Yes   Fri   Lunch     2               14.36
221       13.42   3.48  Female    Yes   Fri   Lunch     2               16.90
222        8.58   1.92    Male    Yes   Fri   Lunch     1               10.50
223       15.98   3.00  Female     No   Fri   Lunch     3               18.98
224       13.42   1.58    Male    Yes   Fri   Lunch     2               15.00
225       16.27   2.50  Female    Yes   Fri   Lunch     2               18.77
226       10.09   2.00  Female    Yes   Fri   Lunch     2               12.09
227       20.45   3.00    Male     No   Sat  Dinner     4               23.45
228       13.28   2.72    Male     No   Sat  Dinner     2               16.00
229       22.12   2.88  Female    Yes   Sat  Dinner     2               25.00
230       24.01   2.00    Male    Yes   Sat  Dinner     4               26.01
231       15.69   3.00    Male    Yes   Sat  Dinner     3               18.69
232       11.61   3.39    Male     No   Sat  Dinner     2               15.00
233       10.77   1.47    Male     No   Sat  Dinner     2               12.24
234       15.53   3.00    Male    Yes   Sat  Dinner     2               18.53
235       10.07   1.25    Male     No   Sat  Dinner     2               11.32
236       12.60   1.00    Male    Yes   Sat  Dinner     2               13.60
237       32.83   1.17    Male    Yes   Sat  Dinner     2               34.00
238       35.83   4.67  Female     No   Sat  Dinner     3               40.50
239       29.03   5.92    Male     No   Sat  Dinner     3               34.95
240       27.18   2.00  Female    Yes   Sat  Dinner     2               29.18
241       22.67   2.00    Male    Yes   Sat  Dinner     2               24.67
242       17.82   1.75    Male     No   Sat  Dinner     2               19.57
243       18.78   3.00  Female     No  Thur  Dinner     2               21.78

Görev 23: total_bill_tip_sum değişkenine göre büyükten küçüğe sıralayınız ve ilk 30 kişiyi yeni bir dataframe'e atayınız.

In [31]:
top_30 = df.sort_values("total_bill_tip_sum", ascending=False).head(30)
top_30

     total_bill    tip     sex smoker   day    time  size  total_bill_tip_sum
170       50.81  10.00    Male    Yes   Sat  Dinner     3               60.81
212       48.33   9.00    Male     No   Sat  Dinner     4               57.33
59        48.27   6.73    Male     No   Sat  Dinner     4               55.00
156       48.17   5.00    Male     No   Sun  Dinner     6               53.17
182       45.35   3.50    Male    Yes   Sun  Dinner     3               48.85
197       43.11   5.00  Female    Yes  Thur   Lunch     4               48.11
23        39.42   7.58    Male     No   Sat  Dinner     4               47.00
102       44.30   2.50  Female    Yes   Sat  Dinner     3               46.80
142       41.19   5.00    Male     No  Thur   Lunch     5               46.19
95        40.17   4.73    Male    Yes   Fri  Dinner     4               44.90
184       40.55   3.00    Male    Yes   Sun  Dinner     2               43.55
112       38.07   4.00    Male     No   Sun  Dinner     3               42.07
207       38.73   3.00    Male    Yes   Sat  Dinner     4               41.73
56        38.01   3.00    Male    Yes   Sat  Dinner     4               41.01
141       34.30   6.70    Male     No  Thur   Lunch     6               41.00
238       35.83   4.67  Female     No   Sat  Dinner     3               40.50
11        35.26   5.00  Female     No   Sun  Dinner     4               40.26
52        34.81   5.20  Female     No   Sun  Dinner     4               40.01
85        34.83   5.17  Female     No  Thur   Lunch     4               40.00
47        32.40   6.00    Male     No   Sun  Dinner     4               38.40
180       34.65   3.68    Male    Yes   Sun  Dinner     4               38.33
179       34.63   3.55    Male    Yes   Sun  Dinner     2               38.18
83        32.68   5.00    Male    Yes  Thur   Lunch     2               37.68
39        31.27   5.00    Male     No   Sat  Dinner     3               36.27
167       31.71   4.50    Male     No   Sun  Dinner     4               36.21
175       32.90   3.11    Male    Yes   Sun  Dinner     2               36.01
44        30.40   5.60    Male     No   Sun  Dinner     4               36.00
173       31.85   3.18    Male    Yes   Sun  Dinner     2               35.03
116       29.93   5.07    Male     No   Sun  Dinner     4               35.00
155       29.85   5.14  Female     No   Sun  Dinner     5               34.99